/*
 * This file is generated by jOOQ.
 */
package az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables;


import az.rock.flyjob.auth.dataAccess.model.jooq.auth.Auth;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.Keys;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.NotificationSettingsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationSettings extends TableImpl<NotificationSettingsRecord> {

    private static final long serialVersionUID = 307569700;

    /**
     * The reference instance of <code>auth.notification_settings</code>
     */
    public static final NotificationSettings NOTİFİCATİON_SETTİNGS = new NotificationSettings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NotificationSettingsRecord> getRecordType() {
        return NotificationSettingsRecord.class;
    }

    /**
     * The column <code>auth.notification_settings.uuid</code>.
     */
    public final TableField<NotificationSettingsRecord, UUID> UUİD = createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>auth.notification_settings.version</code>.
     */
    public final TableField<NotificationSettingsRecord, Long> VERSİON = createField(DSL.name("version"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>auth.notification_settings.process_status</code>.
     */
    public final TableField<NotificationSettingsRecord, String> PROCESS_STATUS = createField(DSL.name("process_status"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>auth.notification_settings.row_status</code>.
     */
    public final TableField<NotificationSettingsRecord, String> ROW_STATUS = createField(DSL.name("row_status"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>auth.notification_settings.created_date</code>.
     */
    public final TableField<NotificationSettingsRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>auth.notification_settings.modification_date</code>.
     */
    public final TableField<NotificationSettingsRecord, LocalDateTime> MODİFİCATİON_DATE = createField(DSL.name("modification_date"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>auth.notification_settings.user_uuid</code>.
     */
    public final TableField<NotificationSettingsRecord, UUID> USER_UUİD = createField(DSL.name("user_uuid"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>auth.notification_settings.notify_me_when_somebody_speaks_about_me</code>.
     */
    public final TableField<NotificationSettingsRecord, Boolean> NOTİFY_ME_WHEN_SOMEBODY_SPEAKS_ABOUT_ME = createField(DSL.name("notify_me_when_somebody_speaks_about_me"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>auth.notification_settings.notify_me_when_somebody_speaks_about_me_on_posts</code>.
     */
    public final TableField<NotificationSettingsRecord, Boolean> NOTİFY_ME_WHEN_SOMEBODY_SPEAKS_ABOUT_ME_ON_POSTS = createField(DSL.name("notify_me_when_somebody_speaks_about_me_on_posts"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>auth.notification_settings.notify_me_when_somebody_speaks_about_me_on_comments</code>.
     */
    public final TableField<NotificationSettingsRecord, Boolean> NOTİFY_ME_WHEN_SOMEBODY_SPEAKS_ABOUT_ME_ON_COMMENTS = createField(DSL.name("notify_me_when_somebody_speaks_about_me_on_comments"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>auth.notification_settings.notify_me_when_somebody_speaks_about_my_replies</code>.
     */
    public final TableField<NotificationSettingsRecord, Boolean> NOTİFY_ME_WHEN_SOMEBODY_SPEAKS_ABOUT_MY_REPLİES = createField(DSL.name("notify_me_when_somebody_speaks_about_my_replies"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * Create a <code>auth.notification_settings</code> table reference
     */
    public NotificationSettings() {
        this(DSL.name("notification_settings"), null);
    }

    /**
     * Create an aliased <code>auth.notification_settings</code> table reference
     */
    public NotificationSettings(String alias) {
        this(DSL.name(alias), NOTİFİCATİON_SETTİNGS);
    }

    /**
     * Create an aliased <code>auth.notification_settings</code> table reference
     */
    public NotificationSettings(Name alias) {
        this(alias, NOTİFİCATİON_SETTİNGS);
    }

    private NotificationSettings(Name alias, Table<NotificationSettingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private NotificationSettings(Name alias, Table<NotificationSettingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> NotificationSettings(Table<O> child, ForeignKey<O, NotificationSettingsRecord> key) {
        super(child, key, NOTİFİCATİON_SETTİNGS);
    }

    @Override
    public Schema getSchema() {
        return Auth.AUTH;
    }

    @Override
    public UniqueKey<NotificationSettingsRecord> getPrimaryKey() {
        return Keys.PK_NOTİFİCATİON_SETTİNGS;
    }

    @Override
    public List<UniqueKey<NotificationSettingsRecord>> getKeys() {
        return Arrays.<UniqueKey<NotificationSettingsRecord>>asList(Keys.PK_NOTİFİCATİON_SETTİNGS);
    }

    @Override
    public List<ForeignKey<NotificationSettingsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<NotificationSettingsRecord, ?>>asList(Keys.NOTİFİCATİON_SETTİNGS__FK_NOTİFİCATİON_SETTİNGS_ON_USER_UUİD);
    }

    public Users users() {
        return new Users(this, Keys.NOTİFİCATİON_SETTİNGS__FK_NOTİFİCATİON_SETTİNGS_ON_USER_UUİD);
    }

    @Override
    public NotificationSettings as(String alias) {
        return new NotificationSettings(DSL.name(alias), this);
    }

    @Override
    public NotificationSettings as(Name alias) {
        return new NotificationSettings(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationSettings rename(String name) {
        return new NotificationSettings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationSettings rename(Name name) {
        return new NotificationSettings(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, Boolean, Boolean, Boolean, Boolean> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
