/*
 * This file is generated by jOOQ.
 */
package az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables;


import az.rock.flyjob.auth.dataAccess.model.jooq.auth.Auth;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.Keys;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.ProfilePicturesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row19;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfilePictures extends TableImpl<ProfilePicturesRecord> {

    private static final long serialVersionUID = 1311651059;

    /**
     * The reference instance of <code>auth.profile_pictures</code>
     */
    public static final ProfilePictures PROFİLE_PİCTURES = new ProfilePictures();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProfilePicturesRecord> getRecordType() {
        return ProfilePicturesRecord.class;
    }

    /**
     * The column <code>auth.profile_pictures.uuid</code>.
     */
    public final TableField<ProfilePicturesRecord, UUID> UUİD = createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>auth.profile_pictures.version</code>.
     */
    public final TableField<ProfilePicturesRecord, Long> VERSİON = createField(DSL.name("version"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>auth.profile_pictures.process_status</code>.
     */
    public final TableField<ProfilePicturesRecord, String> PROCESS_STATUS = createField(DSL.name("process_status"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>auth.profile_pictures.row_status</code>.
     */
    public final TableField<ProfilePicturesRecord, String> ROW_STATUS = createField(DSL.name("row_status"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>auth.profile_pictures.created_date</code>.
     */
    public final TableField<ProfilePicturesRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>auth.profile_pictures.modification_date</code>.
     */
    public final TableField<ProfilePicturesRecord, LocalDateTime> MODİFİCATİON_DATE = createField(DSL.name("modification_date"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>auth.profile_pictures.user_uuid</code>.
     */
    public final TableField<ProfilePicturesRecord, UUID> USER_UUİD = createField(DSL.name("user_uuid"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>auth.profile_pictures.access_modifier</code>.
     */
    public final TableField<ProfilePicturesRecord, String> ACCESS_MODİFİER = createField(DSL.name("access_modifier"), org.jooq.impl.SQLDataType.VARCHAR(32).defaultValue(org.jooq.impl.DSL.field("'ONLY_AUTHENTICATED'::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>auth.profile_pictures.is_current</code>.
     */
    public final TableField<ProfilePicturesRecord, Boolean> İS_CURRENT = createField(DSL.name("is_current"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>auth.profile_pictures.region</code>.
     */
    public final TableField<ProfilePicturesRecord, String> REGİON = createField(DSL.name("region"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.field("'eu-central-1'::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>auth.profile_pictures.file_path</code>.
     */
    public final TableField<ProfilePicturesRecord, String> FİLE_PATH = createField(DSL.name("file_path"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>auth.profile_pictures.file_name</code>.
     */
    public final TableField<ProfilePicturesRecord, String> FİLE_NAME = createField(DSL.name("file_name"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>auth.profile_pictures.file_format</code>.
     */
    public final TableField<ProfilePicturesRecord, String> FİLE_FORMAT = createField(DSL.name("file_format"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>auth.profile_pictures.file_size</code>.
     */
    public final TableField<ProfilePicturesRecord, Long> FİLE_SİZE = createField(DSL.name("file_size"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>auth.profile_pictures.file_url_thumbnail</code>.
     */
    public final TableField<ProfilePicturesRecord, String> FİLE_URL_THUMBNAİL = createField(DSL.name("file_url_thumbnail"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>auth.profile_pictures.file_url_small</code>.
     */
    public final TableField<ProfilePicturesRecord, String> FİLE_URL_SMALL = createField(DSL.name("file_url_small"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>auth.profile_pictures.file_url_medium</code>.
     */
    public final TableField<ProfilePicturesRecord, String> FİLE_URL_MEDİUM = createField(DSL.name("file_url_medium"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>auth.profile_pictures.file_url_large</code>.
     */
    public final TableField<ProfilePicturesRecord, String> FİLE_URL_LARGE = createField(DSL.name("file_url_large"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>auth.profile_pictures.file_url_webp</code>.
     */
    public final TableField<ProfilePicturesRecord, String> FİLE_URL_WEBP = createField(DSL.name("file_url_webp"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>auth.profile_pictures</code> table reference
     */
    public ProfilePictures() {
        this(DSL.name("profile_pictures"), null);
    }

    /**
     * Create an aliased <code>auth.profile_pictures</code> table reference
     */
    public ProfilePictures(String alias) {
        this(DSL.name(alias), PROFİLE_PİCTURES);
    }

    /**
     * Create an aliased <code>auth.profile_pictures</code> table reference
     */
    public ProfilePictures(Name alias) {
        this(alias, PROFİLE_PİCTURES);
    }

    private ProfilePictures(Name alias, Table<ProfilePicturesRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProfilePictures(Name alias, Table<ProfilePicturesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> ProfilePictures(Table<O> child, ForeignKey<O, ProfilePicturesRecord> key) {
        super(child, key, PROFİLE_PİCTURES);
    }

    @Override
    public Schema getSchema() {
        return Auth.AUTH;
    }

    @Override
    public UniqueKey<ProfilePicturesRecord> getPrimaryKey() {
        return Keys.PK_PROFİLE_PİCTURES;
    }

    @Override
    public List<UniqueKey<ProfilePicturesRecord>> getKeys() {
        return Arrays.<UniqueKey<ProfilePicturesRecord>>asList(Keys.PK_PROFİLE_PİCTURES);
    }

    @Override
    public List<ForeignKey<ProfilePicturesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProfilePicturesRecord, ?>>asList(Keys.PROFİLE_PİCTURES__FK_PROFİLE_PİCTURES_ON_USER_UUİD);
    }

    public Users users() {
        return new Users(this, Keys.PROFİLE_PİCTURES__FK_PROFİLE_PİCTURES_ON_USER_UUİD);
    }

    @Override
    public ProfilePictures as(String alias) {
        return new ProfilePictures(DSL.name(alias), this);
    }

    @Override
    public ProfilePictures as(Name alias) {
        return new ProfilePictures(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProfilePictures rename(String name) {
        return new ProfilePictures(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProfilePictures rename(Name name) {
        return new ProfilePictures(name, null);
    }

    // -------------------------------------------------------------------------
    // Row19 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row19<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, String, Boolean, String, String, String, String, Long, String, String, String, String, String> fieldsRow() {
        return (Row19) super.fieldsRow();
    }
}
