/*
 * This file is generated by jOOQ.
 */
package az.rock.flyjob.auth.dataAccess.model.jooq.auth;


import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Emails;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Users;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>auth</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index _3fDX_EMAİLENTİTY_ROW_STATUS = Indexes0._3fDX_EMAİLENTİTY_ROW_STATUS;
    public static final Index _3fDX_USERS_ROW_STATUS = Indexes0._3fDX_USERS_ROW_STATUS;
    public static final Index _3fDX_USERS_USERTYPE = Indexes0._3fDX_USERS_USERTYPE;
    public static final Index İDX_USERS_USERNAME = Indexes0.İDX_USERS_USERNAME;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index _3fDX_EMAİLENTİTY_ROW_STATUS = Internal.createIndex("?dx_emailentity_row_status", Emails.EMAİLS, new OrderField[] { Emails.EMAİLS.ROW_STATUS }, false);
        public static Index _3fDX_USERS_ROW_STATUS = Internal.createIndex("?dx_users_row_status", Users.USERS, new OrderField[] { Users.USERS.ROW_STATUS }, false);
        public static Index _3fDX_USERS_USERTYPE = Internal.createIndex("?dx_users_usertype", Users.USERS, new OrderField[] { Users.USERS.USER_TYPE }, false);
        public static Index İDX_USERS_USERNAME = Internal.createIndex("idx_users_username", Users.USERS, new OrderField[] { Users.USERS.USERNAME }, false);
    }
}
