/*
 * This file is generated by jOOQ.
 */
package az.rock.flyjob.auth.dataAccess.model.jooq.auth;


import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.AccountPlan;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.AccountSettings;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.ActionSettings;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.AuthenticationLogs;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Authorities;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.CoverPictures;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.DetailRole;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Details;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Devices;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Emails;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.GeoPositions;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.NotificationSettings;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Passwords;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.PhoneNumbers;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.ProfilePictures;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.RoleAuthority;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Roles;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.UserSettings;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Users;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.AccountPlanRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.AccountSettingsRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.ActionSettingsRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.AuthenticationLogsRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.AuthoritiesRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.CoverPicturesRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.DetailRoleRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.DetailsRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.DevicesRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.EmailsRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.GeoPositionsRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.NotificationSettingsRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.PasswordsRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.PhoneNumbersRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.ProfilePicturesRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.RoleAuthorityRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.RolesRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.UserSettingsRecord;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>auth</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountPlanRecord> PK_ACCOUNT_PLAN = UniqueKeys0.PK_ACCOUNT_PLAN;
    public static final UniqueKey<AccountSettingsRecord> PK_ACCOUNT_SETTİNGS = UniqueKeys0.PK_ACCOUNT_SETTİNGS;
    public static final UniqueKey<ActionSettingsRecord> PK_ACTİON_SETTİNGS = UniqueKeys0.PK_ACTİON_SETTİNGS;
    public static final UniqueKey<AuthenticationLogsRecord> PK_AUTHENTİCATİON_LOGS = UniqueKeys0.PK_AUTHENTİCATİON_LOGS;
    public static final UniqueKey<AuthoritiesRecord> PK_AUTHORİTİES = UniqueKeys0.PK_AUTHORİTİES;
    public static final UniqueKey<AuthoritiesRecord> UC_AUTHORİTİES_PERMİSSİON = UniqueKeys0.UC_AUTHORİTİES_PERMİSSİON;
    public static final UniqueKey<CoverPicturesRecord> PK_COVER_PİCTURES = UniqueKeys0.PK_COVER_PİCTURES;
    public static final UniqueKey<DetailRoleRecord> PK_DETAİL_ROLE = UniqueKeys0.PK_DETAİL_ROLE;
    public static final UniqueKey<DetailsRecord> PK_DETAİLS = UniqueKeys0.PK_DETAİLS;
    public static final UniqueKey<DevicesRecord> PK_DEVİCES = UniqueKeys0.PK_DEVİCES;
    public static final UniqueKey<EmailsRecord> PK_EMAİLS = UniqueKeys0.PK_EMAİLS;
    public static final UniqueKey<EmailsRecord> UC_EMAİLS_EMAİL = UniqueKeys0.UC_EMAİLS_EMAİL;
    public static final UniqueKey<GeoPositionsRecord> PK_GEO_POSİTİONS = UniqueKeys0.PK_GEO_POSİTİONS;
    public static final UniqueKey<NotificationSettingsRecord> PK_NOTİFİCATİON_SETTİNGS = UniqueKeys0.PK_NOTİFİCATİON_SETTİNGS;
    public static final UniqueKey<PasswordsRecord> PK_PASSWORDS = UniqueKeys0.PK_PASSWORDS;
    public static final UniqueKey<PhoneNumbersRecord> PK_PHONE_NUMBERS = UniqueKeys0.PK_PHONE_NUMBERS;
    public static final UniqueKey<ProfilePicturesRecord> PK_PROFİLE_PİCTURES = UniqueKeys0.PK_PROFİLE_PİCTURES;
    public static final UniqueKey<RoleAuthorityRecord> PK_ROLE_AUTHORİTY = UniqueKeys0.PK_ROLE_AUTHORİTY;
    public static final UniqueKey<RolesRecord> PK_ROLES = UniqueKeys0.PK_ROLES;
    public static final UniqueKey<UserSettingsRecord> PK_USER_SETTİNGS = UniqueKeys0.PK_USER_SETTİNGS;
    public static final UniqueKey<UsersRecord> PK_USERS = UniqueKeys0.PK_USERS;
    public static final UniqueKey<UsersRecord> UC_USERS_KEY = UniqueKeys0.UC_USERS_KEY;
    public static final UniqueKey<UsersRecord> UC_USERS_USERNAME = UniqueKeys0.UC_USERS_USERNAME;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AccountPlanRecord, UsersRecord> ACCOUNT_PLAN__FK_ACCOUNT_PLAN_ON_USER_UUİD = ForeignKeys0.ACCOUNT_PLAN__FK_ACCOUNT_PLAN_ON_USER_UUİD;
    public static final ForeignKey<AccountSettingsRecord, UsersRecord> ACCOUNT_SETTİNGS__FK_ACCOUNT_SETTİNGS_ON_USER_UUİD = ForeignKeys0.ACCOUNT_SETTİNGS__FK_ACCOUNT_SETTİNGS_ON_USER_UUİD;
    public static final ForeignKey<ActionSettingsRecord, UsersRecord> ACTİON_SETTİNGS__FK_ACTİON_SETTİNGS_ON_USER_UUİD = ForeignKeys0.ACTİON_SETTİNGS__FK_ACTİON_SETTİNGS_ON_USER_UUİD;
    public static final ForeignKey<AuthenticationLogsRecord, DevicesRecord> AUTHENTİCATİON_LOGS__FK_AUTHENTİCATİON_LOGS_ON_DEVİCE_UUİD = ForeignKeys0.AUTHENTİCATİON_LOGS__FK_AUTHENTİCATİON_LOGS_ON_DEVİCE_UUİD;
    public static final ForeignKey<CoverPicturesRecord, UsersRecord> COVER_PİCTURES__FK_COVER_PİCTURES_ON_USER_UUİD = ForeignKeys0.COVER_PİCTURES__FK_COVER_PİCTURES_ON_USER_UUİD;
    public static final ForeignKey<DetailRoleRecord, DetailsRecord> DETAİL_ROLE__FK_DETROL_ON_DETAİL_ENTİTY = ForeignKeys0.DETAİL_ROLE__FK_DETROL_ON_DETAİL_ENTİTY;
    public static final ForeignKey<DetailRoleRecord, RolesRecord> DETAİL_ROLE__FK_DETROL_ON_ROLE_ENTİTY = ForeignKeys0.DETAİL_ROLE__FK_DETROL_ON_ROLE_ENTİTY;
    public static final ForeignKey<DetailsRecord, UsersRecord> DETAİLS__FK_DETAİLS_ON_USER_UUİD = ForeignKeys0.DETAİLS__FK_DETAİLS_ON_USER_UUİD;
    public static final ForeignKey<DevicesRecord, UsersRecord> DEVİCES__FK_DEVİCES_ON_USER_UUİD = ForeignKeys0.DEVİCES__FK_DEVİCES_ON_USER_UUİD;
    public static final ForeignKey<EmailsRecord, UsersRecord> EMAİLS__FK_EMAİLS_ON_USER_UUİD = ForeignKeys0.EMAİLS__FK_EMAİLS_ON_USER_UUİD;
    public static final ForeignKey<GeoPositionsRecord, DevicesRecord> GEO_POSİTİONS__FK_GEO_POSİTİONS_ON_DEVİCEENTİTY_UUİD = ForeignKeys0.GEO_POSİTİONS__FK_GEO_POSİTİONS_ON_DEVİCEENTİTY_UUİD;
    public static final ForeignKey<NotificationSettingsRecord, UsersRecord> NOTİFİCATİON_SETTİNGS__FK_NOTİFİCATİON_SETTİNGS_ON_USER_UUİD = ForeignKeys0.NOTİFİCATİON_SETTİNGS__FK_NOTİFİCATİON_SETTİNGS_ON_USER_UUİD;
    public static final ForeignKey<PasswordsRecord, UsersRecord> PASSWORDS__FK_PASSWORDS_ON_USER_UUİD = ForeignKeys0.PASSWORDS__FK_PASSWORDS_ON_USER_UUİD;
    public static final ForeignKey<PhoneNumbersRecord, UsersRecord> PHONE_NUMBERS__FK_PHONE_NUMBERS_ON_USER_UUİD = ForeignKeys0.PHONE_NUMBERS__FK_PHONE_NUMBERS_ON_USER_UUİD;
    public static final ForeignKey<ProfilePicturesRecord, UsersRecord> PROFİLE_PİCTURES__FK_PROFİLE_PİCTURES_ON_USER_UUİD = ForeignKeys0.PROFİLE_PİCTURES__FK_PROFİLE_PİCTURES_ON_USER_UUİD;
    public static final ForeignKey<RoleAuthorityRecord, AuthoritiesRecord> ROLE_AUTHORİTY__FK_ROLAUT_ON_AUTHORİTY_ENTİTY = ForeignKeys0.ROLE_AUTHORİTY__FK_ROLAUT_ON_AUTHORİTY_ENTİTY;
    public static final ForeignKey<RoleAuthorityRecord, RolesRecord> ROLE_AUTHORİTY__FK_ROLAUT_ON_ROLE_ENTİTY = ForeignKeys0.ROLE_AUTHORİTY__FK_ROLAUT_ON_ROLE_ENTİTY;
    public static final ForeignKey<UserSettingsRecord, UsersRecord> USER_SETTİNGS__FK_USER_SETTİNGS_ON_USER_UUİD = ForeignKeys0.USER_SETTİNGS__FK_USER_SETTİNGS_ON_USER_UUİD;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountPlanRecord> PK_ACCOUNT_PLAN = Internal.createUniqueKey(AccountPlan.ACCOUNT_PLAN, "pk_account_plan", new TableField[] { AccountPlan.ACCOUNT_PLAN.UUİD }, true);
        public static final UniqueKey<AccountSettingsRecord> PK_ACCOUNT_SETTİNGS = Internal.createUniqueKey(AccountSettings.ACCOUNT_SETTİNGS, "pk_account_settings", new TableField[] { AccountSettings.ACCOUNT_SETTİNGS.UUİD }, true);
        public static final UniqueKey<ActionSettingsRecord> PK_ACTİON_SETTİNGS = Internal.createUniqueKey(ActionSettings.ACTİON_SETTİNGS, "pk_action_settings", new TableField[] { ActionSettings.ACTİON_SETTİNGS.UUİD }, true);
        public static final UniqueKey<AuthenticationLogsRecord> PK_AUTHENTİCATİON_LOGS = Internal.createUniqueKey(AuthenticationLogs.AUTHENTİCATİON_LOGS, "pk_authentication_logs", new TableField[] { AuthenticationLogs.AUTHENTİCATİON_LOGS.UUİD }, true);
        public static final UniqueKey<AuthoritiesRecord> PK_AUTHORİTİES = Internal.createUniqueKey(Authorities.AUTHORİTİES, "pk_authorities", new TableField[] { Authorities.AUTHORİTİES.UUİD }, true);
        public static final UniqueKey<AuthoritiesRecord> UC_AUTHORİTİES_PERMİSSİON = Internal.createUniqueKey(Authorities.AUTHORİTİES, "uc_authorities_permission", new TableField[] { Authorities.AUTHORİTİES.PERMİSSİON }, true);
        public static final UniqueKey<CoverPicturesRecord> PK_COVER_PİCTURES = Internal.createUniqueKey(CoverPictures.COVER_PİCTURES, "pk_cover_pictures", new TableField[] { CoverPictures.COVER_PİCTURES.UUİD }, true);
        public static final UniqueKey<DetailRoleRecord> PK_DETAİL_ROLE = Internal.createUniqueKey(DetailRole.DETAİL_ROLE, "pk_detail_role", new TableField[] { DetailRole.DETAİL_ROLE.DETAİL_UUİD, DetailRole.DETAİL_ROLE.ROLE_UUİD }, true);
        public static final UniqueKey<DetailsRecord> PK_DETAİLS = Internal.createUniqueKey(Details.DETAİLS, "pk_details", new TableField[] { Details.DETAİLS.UUİD }, true);
        public static final UniqueKey<DevicesRecord> PK_DEVİCES = Internal.createUniqueKey(Devices.DEVİCES, "pk_devices", new TableField[] { Devices.DEVİCES.UUİD }, true);
        public static final UniqueKey<EmailsRecord> PK_EMAİLS = Internal.createUniqueKey(Emails.EMAİLS, "pk_emails", new TableField[] { Emails.EMAİLS.UUİD }, true);
        public static final UniqueKey<EmailsRecord> UC_EMAİLS_EMAİL = Internal.createUniqueKey(Emails.EMAİLS, "uc_emails_email", new TableField[] { Emails.EMAİLS.EMAİL }, true);
        public static final UniqueKey<GeoPositionsRecord> PK_GEO_POSİTİONS = Internal.createUniqueKey(GeoPositions.GEO_POSİTİONS, "pk_geo_positions", new TableField[] { GeoPositions.GEO_POSİTİONS.UUİD }, true);
        public static final UniqueKey<NotificationSettingsRecord> PK_NOTİFİCATİON_SETTİNGS = Internal.createUniqueKey(NotificationSettings.NOTİFİCATİON_SETTİNGS, "pk_notification_settings", new TableField[] { NotificationSettings.NOTİFİCATİON_SETTİNGS.UUİD }, true);
        public static final UniqueKey<PasswordsRecord> PK_PASSWORDS = Internal.createUniqueKey(Passwords.PASSWORDS, "pk_passwords", new TableField[] { Passwords.PASSWORDS.UUİD }, true);
        public static final UniqueKey<PhoneNumbersRecord> PK_PHONE_NUMBERS = Internal.createUniqueKey(PhoneNumbers.PHONE_NUMBERS, "pk_phone_numbers", new TableField[] { PhoneNumbers.PHONE_NUMBERS.UUİD }, true);
        public static final UniqueKey<ProfilePicturesRecord> PK_PROFİLE_PİCTURES = Internal.createUniqueKey(ProfilePictures.PROFİLE_PİCTURES, "pk_profile_pictures", new TableField[] { ProfilePictures.PROFİLE_PİCTURES.UUİD }, true);
        public static final UniqueKey<RoleAuthorityRecord> PK_ROLE_AUTHORİTY = Internal.createUniqueKey(RoleAuthority.ROLE_AUTHORİTY, "pk_role_authority", new TableField[] { RoleAuthority.ROLE_AUTHORİTY.AUTHORİTY_İD, RoleAuthority.ROLE_AUTHORİTY.ROLE_İD }, true);
        public static final UniqueKey<RolesRecord> PK_ROLES = Internal.createUniqueKey(Roles.ROLES, "pk_roles", new TableField[] { Roles.ROLES.UUİD }, true);
        public static final UniqueKey<UserSettingsRecord> PK_USER_SETTİNGS = Internal.createUniqueKey(UserSettings.USER_SETTİNGS, "pk_user_settings", new TableField[] { UserSettings.USER_SETTİNGS.UUİD }, true);
        public static final UniqueKey<UsersRecord> PK_USERS = Internal.createUniqueKey(Users.USERS, "pk_users", new TableField[] { Users.USERS.UUİD }, true);
        public static final UniqueKey<UsersRecord> UC_USERS_KEY = Internal.createUniqueKey(Users.USERS, "uc_users_key", new TableField[] { Users.USERS.KEY }, true);
        public static final UniqueKey<UsersRecord> UC_USERS_USERNAME = Internal.createUniqueKey(Users.USERS, "uc_users_username", new TableField[] { Users.USERS.USERNAME }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AccountPlanRecord, UsersRecord> ACCOUNT_PLAN__FK_ACCOUNT_PLAN_ON_USER_UUİD = Internal.createForeignKey(Keys.PK_USERS, AccountPlan.ACCOUNT_PLAN, "fk_account_plan_on_user_uuid", new TableField[] { AccountPlan.ACCOUNT_PLAN.USER_UUİD }, true);
        public static final ForeignKey<AccountSettingsRecord, UsersRecord> ACCOUNT_SETTİNGS__FK_ACCOUNT_SETTİNGS_ON_USER_UUİD = Internal.createForeignKey(Keys.PK_USERS, AccountSettings.ACCOUNT_SETTİNGS, "fk_account_settings_on_user_uuid", new TableField[] { AccountSettings.ACCOUNT_SETTİNGS.USER_UUİD }, true);
        public static final ForeignKey<ActionSettingsRecord, UsersRecord> ACTİON_SETTİNGS__FK_ACTİON_SETTİNGS_ON_USER_UUİD = Internal.createForeignKey(Keys.PK_USERS, ActionSettings.ACTİON_SETTİNGS, "fk_action_settings_on_user_uuid", new TableField[] { ActionSettings.ACTİON_SETTİNGS.USER_UUİD }, true);
        public static final ForeignKey<AuthenticationLogsRecord, DevicesRecord> AUTHENTİCATİON_LOGS__FK_AUTHENTİCATİON_LOGS_ON_DEVİCE_UUİD = Internal.createForeignKey(Keys.PK_DEVİCES, AuthenticationLogs.AUTHENTİCATİON_LOGS, "fk_authentication_logs_on_device_uuid", new TableField[] { AuthenticationLogs.AUTHENTİCATİON_LOGS.DEVİCE_UUİD }, true);
        public static final ForeignKey<CoverPicturesRecord, UsersRecord> COVER_PİCTURES__FK_COVER_PİCTURES_ON_USER_UUİD = Internal.createForeignKey(Keys.PK_USERS, CoverPictures.COVER_PİCTURES, "fk_cover_pictures_on_user_uuid", new TableField[] { CoverPictures.COVER_PİCTURES.USER_UUİD }, true);
        public static final ForeignKey<DetailRoleRecord, DetailsRecord> DETAİL_ROLE__FK_DETROL_ON_DETAİL_ENTİTY = Internal.createForeignKey(Keys.PK_DETAİLS, DetailRole.DETAİL_ROLE, "fk_detrol_on_detail_entity", new TableField[] { DetailRole.DETAİL_ROLE.DETAİL_UUİD }, true);
        public static final ForeignKey<DetailRoleRecord, RolesRecord> DETAİL_ROLE__FK_DETROL_ON_ROLE_ENTİTY = Internal.createForeignKey(Keys.PK_ROLES, DetailRole.DETAİL_ROLE, "fk_detrol_on_role_entity", new TableField[] { DetailRole.DETAİL_ROLE.ROLE_UUİD }, true);
        public static final ForeignKey<DetailsRecord, UsersRecord> DETAİLS__FK_DETAİLS_ON_USER_UUİD = Internal.createForeignKey(Keys.PK_USERS, Details.DETAİLS, "fk_details_on_user_uuid", new TableField[] { Details.DETAİLS.USER_UUİD }, true);
        public static final ForeignKey<DevicesRecord, UsersRecord> DEVİCES__FK_DEVİCES_ON_USER_UUİD = Internal.createForeignKey(Keys.PK_USERS, Devices.DEVİCES, "fk_devices_on_user_uuid", new TableField[] { Devices.DEVİCES.USER_UUİD }, true);
        public static final ForeignKey<EmailsRecord, UsersRecord> EMAİLS__FK_EMAİLS_ON_USER_UUİD = Internal.createForeignKey(Keys.PK_USERS, Emails.EMAİLS, "fk_emails_on_user_uuid", new TableField[] { Emails.EMAİLS.USER_UUİD }, true);
        public static final ForeignKey<GeoPositionsRecord, DevicesRecord> GEO_POSİTİONS__FK_GEO_POSİTİONS_ON_DEVİCEENTİTY_UUİD = Internal.createForeignKey(Keys.PK_DEVİCES, GeoPositions.GEO_POSİTİONS, "fk_geo_positions_on_deviceentity_uuid", new TableField[] { GeoPositions.GEO_POSİTİONS.DEVİCE_ENTİTY_UUİD }, true);
        public static final ForeignKey<NotificationSettingsRecord, UsersRecord> NOTİFİCATİON_SETTİNGS__FK_NOTİFİCATİON_SETTİNGS_ON_USER_UUİD = Internal.createForeignKey(Keys.PK_USERS, NotificationSettings.NOTİFİCATİON_SETTİNGS, "fk_notification_settings_on_user_uuid", new TableField[] { NotificationSettings.NOTİFİCATİON_SETTİNGS.USER_UUİD }, true);
        public static final ForeignKey<PasswordsRecord, UsersRecord> PASSWORDS__FK_PASSWORDS_ON_USER_UUİD = Internal.createForeignKey(Keys.PK_USERS, Passwords.PASSWORDS, "fk_passwords_on_user_uuid", new TableField[] { Passwords.PASSWORDS.USER_UUİD }, true);
        public static final ForeignKey<PhoneNumbersRecord, UsersRecord> PHONE_NUMBERS__FK_PHONE_NUMBERS_ON_USER_UUİD = Internal.createForeignKey(Keys.PK_USERS, PhoneNumbers.PHONE_NUMBERS, "fk_phone_numbers_on_user_uuid", new TableField[] { PhoneNumbers.PHONE_NUMBERS.USER_UUİD }, true);
        public static final ForeignKey<ProfilePicturesRecord, UsersRecord> PROFİLE_PİCTURES__FK_PROFİLE_PİCTURES_ON_USER_UUİD = Internal.createForeignKey(Keys.PK_USERS, ProfilePictures.PROFİLE_PİCTURES, "fk_profile_pictures_on_user_uuid", new TableField[] { ProfilePictures.PROFİLE_PİCTURES.USER_UUİD }, true);
        public static final ForeignKey<RoleAuthorityRecord, AuthoritiesRecord> ROLE_AUTHORİTY__FK_ROLAUT_ON_AUTHORİTY_ENTİTY = Internal.createForeignKey(Keys.PK_AUTHORİTİES, RoleAuthority.ROLE_AUTHORİTY, "fk_rolaut_on_authority_entity", new TableField[] { RoleAuthority.ROLE_AUTHORİTY.AUTHORİTY_İD }, true);
        public static final ForeignKey<RoleAuthorityRecord, RolesRecord> ROLE_AUTHORİTY__FK_ROLAUT_ON_ROLE_ENTİTY = Internal.createForeignKey(Keys.PK_ROLES, RoleAuthority.ROLE_AUTHORİTY, "fk_rolaut_on_role_entity", new TableField[] { RoleAuthority.ROLE_AUTHORİTY.ROLE_İD }, true);
        public static final ForeignKey<UserSettingsRecord, UsersRecord> USER_SETTİNGS__FK_USER_SETTİNGS_ON_USER_UUİD = Internal.createForeignKey(Keys.PK_USERS, UserSettings.USER_SETTİNGS, "fk_user_settings_on_user_uuid", new TableField[] { UserSettings.USER_SETTİNGS.USER_UUİD }, true);
    }
}
