/*
 * This file is generated by jOOQ.
 */
package az.rock.flyjob.auth.dataAccess.model.jooq.auth;


import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.AccountPlan;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.AccountSettings;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.ActionSettings;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.AuthenticationLogs;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Authorities;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.CoverPictures;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.DetailRole;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Details;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Devices;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Emails;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.GeoPositions;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.NotificationSettings;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Passwords;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.PhoneNumbers;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.ProfilePictures;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.RoleAuthority;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Roles;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.UserSettings;
import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Users;


/**
 * Convenience access to all tables in auth
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>auth.account_plan</code>.
     */
    public static final AccountPlan ACCOUNT_PLAN = AccountPlan.ACCOUNT_PLAN;

    /**
     * The table <code>auth.account_settings</code>.
     */
    public static final AccountSettings ACCOUNT_SETTİNGS = AccountSettings.ACCOUNT_SETTİNGS;

    /**
     * The table <code>auth.action_settings</code>.
     */
    public static final ActionSettings ACTİON_SETTİNGS = ActionSettings.ACTİON_SETTİNGS;

    /**
     * The table <code>auth.authentication_logs</code>.
     */
    public static final AuthenticationLogs AUTHENTİCATİON_LOGS = AuthenticationLogs.AUTHENTİCATİON_LOGS;

    /**
     * The table <code>auth.authorities</code>.
     */
    public static final Authorities AUTHORİTİES = Authorities.AUTHORİTİES;

    /**
     * The table <code>auth.cover_pictures</code>.
     */
    public static final CoverPictures COVER_PİCTURES = CoverPictures.COVER_PİCTURES;

    /**
     * The table <code>auth.detail_role</code>.
     */
    public static final DetailRole DETAİL_ROLE = DetailRole.DETAİL_ROLE;

    /**
     * The table <code>auth.details</code>.
     */
    public static final Details DETAİLS = Details.DETAİLS;

    /**
     * The table <code>auth.devices</code>.
     */
    public static final Devices DEVİCES = Devices.DEVİCES;

    /**
     * The table <code>auth.emails</code>.
     */
    public static final Emails EMAİLS = Emails.EMAİLS;

    /**
     * The table <code>auth.geo_positions</code>.
     */
    public static final GeoPositions GEO_POSİTİONS = GeoPositions.GEO_POSİTİONS;

    /**
     * The table <code>auth.notification_settings</code>.
     */
    public static final NotificationSettings NOTİFİCATİON_SETTİNGS = NotificationSettings.NOTİFİCATİON_SETTİNGS;

    /**
     * The table <code>auth.passwords</code>.
     */
    public static final Passwords PASSWORDS = Passwords.PASSWORDS;

    /**
     * The table <code>auth.phone_numbers</code>.
     */
    public static final PhoneNumbers PHONE_NUMBERS = PhoneNumbers.PHONE_NUMBERS;

    /**
     * The table <code>auth.profile_pictures</code>.
     */
    public static final ProfilePictures PROFİLE_PİCTURES = ProfilePictures.PROFİLE_PİCTURES;

    /**
     * The table <code>auth.role_authority</code>.
     */
    public static final RoleAuthority ROLE_AUTHORİTY = RoleAuthority.ROLE_AUTHORİTY;

    /**
     * The table <code>auth.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>auth.user_settings</code>.
     */
    public static final UserSettings USER_SETTİNGS = UserSettings.USER_SETTİNGS;

    /**
     * The table <code>auth.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
