/*
 * This file is generated by jOOQ.
 */
package az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records;


import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.AccountSettings;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountSettingsRecord extends UpdatableRecordImpl<AccountSettingsRecord> implements Record12<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, Boolean, Boolean, Boolean, Boolean, Boolean> {

    private static final long serialVersionUID = 1734435446;

    /**
     * Setter for <code>auth.account_settings.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.account_settings.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>auth.account_settings.version</code>.
     */
    public void setVersion(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.account_settings.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>auth.account_settings.process_status</code>.
     */
    public void setProcessStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.account_settings.process_status</code>.
     */
    public String getProcessStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>auth.account_settings.row_status</code>.
     */
    public void setRowStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.account_settings.row_status</code>.
     */
    public String getRowStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>auth.account_settings.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.account_settings.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>auth.account_settings.modification_date</code>.
     */
    public void setModificationDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>auth.account_settings.modification_date</code>.
     */
    public LocalDateTime getModificationDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>auth.account_settings.user_uuid</code>.
     */
    public void setUserUuid(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>auth.account_settings.user_uuid</code>.
     */
    public UUID getUserUuid() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>auth.account_settings.is_possible_to_find_me_by_email</code>.
     */
    public void setİsPossibleToFindMeByEmail(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>auth.account_settings.is_possible_to_find_me_by_email</code>.
     */
    public Boolean getİsPossibleToFindMeByEmail() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>auth.account_settings.is_possible_to_find_me_by_phone_number</code>.
     */
    public void setİsPossibleToFindMeByPhoneNumber(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>auth.account_settings.is_possible_to_find_me_by_phone_number</code>.
     */
    public Boolean getİsPossibleToFindMeByPhoneNumber() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>auth.account_settings.is_possible_to_find_me_by_user_name</code>.
     */
    public void setİsPossibleToFindMeByUserName(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>auth.account_settings.is_possible_to_find_me_by_user_name</code>.
     */
    public Boolean getİsPossibleToFindMeByUserName() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>auth.account_settings.is_possible_to_find_me_by_full_name</code>.
     */
    public void setİsPossibleToFindMeByFullName(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>auth.account_settings.is_possible_to_find_me_by_full_name</code>.
     */
    public Boolean getİsPossibleToFindMeByFullName() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>auth.account_settings.is_possible_to_find_me_by_location</code>.
     */
    public void setİsPossibleToFindMeByLocation(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>auth.account_settings.is_possible_to_find_me_by_location</code>.
     */
    public Boolean getİsPossibleToFindMeByLocation() {
        return (Boolean) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, Boolean, Boolean, Boolean, Boolean, Boolean> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, Boolean, Boolean, Boolean, Boolean, Boolean> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AccountSettings.ACCOUNT_SETTİNGS.UUİD;
    }

    @Override
    public Field<Long> field2() {
        return AccountSettings.ACCOUNT_SETTİNGS.VERSİON;
    }

    @Override
    public Field<String> field3() {
        return AccountSettings.ACCOUNT_SETTİNGS.PROCESS_STATUS;
    }

    @Override
    public Field<String> field4() {
        return AccountSettings.ACCOUNT_SETTİNGS.ROW_STATUS;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return AccountSettings.ACCOUNT_SETTİNGS.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return AccountSettings.ACCOUNT_SETTİNGS.MODİFİCATİON_DATE;
    }

    @Override
    public Field<UUID> field7() {
        return AccountSettings.ACCOUNT_SETTİNGS.USER_UUİD;
    }

    @Override
    public Field<Boolean> field8() {
        return AccountSettings.ACCOUNT_SETTİNGS.İS_POSSİBLE_TO_FİND_ME_BY_EMAİL;
    }

    @Override
    public Field<Boolean> field9() {
        return AccountSettings.ACCOUNT_SETTİNGS.İS_POSSİBLE_TO_FİND_ME_BY_PHONE_NUMBER;
    }

    @Override
    public Field<Boolean> field10() {
        return AccountSettings.ACCOUNT_SETTİNGS.İS_POSSİBLE_TO_FİND_ME_BY_USER_NAME;
    }

    @Override
    public Field<Boolean> field11() {
        return AccountSettings.ACCOUNT_SETTİNGS.İS_POSSİBLE_TO_FİND_ME_BY_FULL_NAME;
    }

    @Override
    public Field<Boolean> field12() {
        return AccountSettings.ACCOUNT_SETTİNGS.İS_POSSİBLE_TO_FİND_ME_BY_LOCATİON;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public Long component2() {
        return getVersion();
    }

    @Override
    public String component3() {
        return getProcessStatus();
    }

    @Override
    public String component4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component6() {
        return getModificationDate();
    }

    @Override
    public UUID component7() {
        return getUserUuid();
    }

    @Override
    public Boolean component8() {
        return getİsPossibleToFindMeByEmail();
    }

    @Override
    public Boolean component9() {
        return getİsPossibleToFindMeByPhoneNumber();
    }

    @Override
    public Boolean component10() {
        return getİsPossibleToFindMeByUserName();
    }

    @Override
    public Boolean component11() {
        return getİsPossibleToFindMeByFullName();
    }

    @Override
    public Boolean component12() {
        return getİsPossibleToFindMeByLocation();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public Long value2() {
        return getVersion();
    }

    @Override
    public String value3() {
        return getProcessStatus();
    }

    @Override
    public String value4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value6() {
        return getModificationDate();
    }

    @Override
    public UUID value7() {
        return getUserUuid();
    }

    @Override
    public Boolean value8() {
        return getİsPossibleToFindMeByEmail();
    }

    @Override
    public Boolean value9() {
        return getİsPossibleToFindMeByPhoneNumber();
    }

    @Override
    public Boolean value10() {
        return getİsPossibleToFindMeByUserName();
    }

    @Override
    public Boolean value11() {
        return getİsPossibleToFindMeByFullName();
    }

    @Override
    public Boolean value12() {
        return getİsPossibleToFindMeByLocation();
    }

    @Override
    public AccountSettingsRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public AccountSettingsRecord value2(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public AccountSettingsRecord value3(String value) {
        setProcessStatus(value);
        return this;
    }

    @Override
    public AccountSettingsRecord value4(String value) {
        setRowStatus(value);
        return this;
    }

    @Override
    public AccountSettingsRecord value5(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public AccountSettingsRecord value6(LocalDateTime value) {
        setModificationDate(value);
        return this;
    }

    @Override
    public AccountSettingsRecord value7(UUID value) {
        setUserUuid(value);
        return this;
    }

    @Override
    public AccountSettingsRecord value8(Boolean value) {
        setİsPossibleToFindMeByEmail(value);
        return this;
    }

    @Override
    public AccountSettingsRecord value9(Boolean value) {
        setİsPossibleToFindMeByPhoneNumber(value);
        return this;
    }

    @Override
    public AccountSettingsRecord value10(Boolean value) {
        setİsPossibleToFindMeByUserName(value);
        return this;
    }

    @Override
    public AccountSettingsRecord value11(Boolean value) {
        setİsPossibleToFindMeByFullName(value);
        return this;
    }

    @Override
    public AccountSettingsRecord value12(Boolean value) {
        setİsPossibleToFindMeByLocation(value);
        return this;
    }

    @Override
    public AccountSettingsRecord values(UUID value1, Long value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, UUID value7, Boolean value8, Boolean value9, Boolean value10, Boolean value11, Boolean value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountSettingsRecord
     */
    public AccountSettingsRecord() {
        super(AccountSettings.ACCOUNT_SETTİNGS);
    }

    /**
     * Create a detached, initialised AccountSettingsRecord
     */
    public AccountSettingsRecord(UUID uuid, Long version, String processStatus, String rowStatus, LocalDateTime createdDate, LocalDateTime modificationDate, UUID userUuid, Boolean isPossibleToFindMeByEmail, Boolean isPossibleToFindMeByPhoneNumber, Boolean isPossibleToFindMeByUserName, Boolean isPossibleToFindMeByFullName, Boolean isPossibleToFindMeByLocation) {
        super(AccountSettings.ACCOUNT_SETTİNGS);

        set(0, uuid);
        set(1, version);
        set(2, processStatus);
        set(3, rowStatus);
        set(4, createdDate);
        set(5, modificationDate);
        set(6, userUuid);
        set(7, isPossibleToFindMeByEmail);
        set(8, isPossibleToFindMeByPhoneNumber);
        set(9, isPossibleToFindMeByUserName);
        set(10, isPossibleToFindMeByFullName);
        set(11, isPossibleToFindMeByLocation);
    }
}
