/*
 * This file is generated by jOOQ.
 */
package az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records;


import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.AuthenticationLogs;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthenticationLogsRecord extends UpdatableRecordImpl<AuthenticationLogsRecord> implements Record8<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, UUID> {

    private static final long serialVersionUID = -1549535043;

    /**
     * Setter for <code>auth.authentication_logs.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.authentication_logs.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>auth.authentication_logs.version</code>.
     */
    public void setVersion(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.authentication_logs.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>auth.authentication_logs.process_status</code>.
     */
    public void setProcessStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.authentication_logs.process_status</code>.
     */
    public String getProcessStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>auth.authentication_logs.row_status</code>.
     */
    public void setRowStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.authentication_logs.row_status</code>.
     */
    public String getRowStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>auth.authentication_logs.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.authentication_logs.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>auth.authentication_logs.modification_date</code>.
     */
    public void setModificationDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>auth.authentication_logs.modification_date</code>.
     */
    public LocalDateTime getModificationDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>auth.authentication_logs.device_uuid</code>.
     */
    public void setDeviceUuid(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>auth.authentication_logs.device_uuid</code>.
     */
    public UUID getDeviceUuid() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>auth.authentication_logs.device_token</code>.
     */
    public void setDeviceToken(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>auth.authentication_logs.device_token</code>.
     */
    public UUID getDeviceToken() {
        return (UUID) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, UUID> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, UUID> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AuthenticationLogs.AUTHENTİCATİON_LOGS.UUİD;
    }

    @Override
    public Field<Long> field2() {
        return AuthenticationLogs.AUTHENTİCATİON_LOGS.VERSİON;
    }

    @Override
    public Field<String> field3() {
        return AuthenticationLogs.AUTHENTİCATİON_LOGS.PROCESS_STATUS;
    }

    @Override
    public Field<String> field4() {
        return AuthenticationLogs.AUTHENTİCATİON_LOGS.ROW_STATUS;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return AuthenticationLogs.AUTHENTİCATİON_LOGS.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return AuthenticationLogs.AUTHENTİCATİON_LOGS.MODİFİCATİON_DATE;
    }

    @Override
    public Field<UUID> field7() {
        return AuthenticationLogs.AUTHENTİCATİON_LOGS.DEVİCE_UUİD;
    }

    @Override
    public Field<UUID> field8() {
        return AuthenticationLogs.AUTHENTİCATİON_LOGS.DEVİCE_TOKEN;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public Long component2() {
        return getVersion();
    }

    @Override
    public String component3() {
        return getProcessStatus();
    }

    @Override
    public String component4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component6() {
        return getModificationDate();
    }

    @Override
    public UUID component7() {
        return getDeviceUuid();
    }

    @Override
    public UUID component8() {
        return getDeviceToken();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public Long value2() {
        return getVersion();
    }

    @Override
    public String value3() {
        return getProcessStatus();
    }

    @Override
    public String value4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value6() {
        return getModificationDate();
    }

    @Override
    public UUID value7() {
        return getDeviceUuid();
    }

    @Override
    public UUID value8() {
        return getDeviceToken();
    }

    @Override
    public AuthenticationLogsRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public AuthenticationLogsRecord value2(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public AuthenticationLogsRecord value3(String value) {
        setProcessStatus(value);
        return this;
    }

    @Override
    public AuthenticationLogsRecord value4(String value) {
        setRowStatus(value);
        return this;
    }

    @Override
    public AuthenticationLogsRecord value5(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public AuthenticationLogsRecord value6(LocalDateTime value) {
        setModificationDate(value);
        return this;
    }

    @Override
    public AuthenticationLogsRecord value7(UUID value) {
        setDeviceUuid(value);
        return this;
    }

    @Override
    public AuthenticationLogsRecord value8(UUID value) {
        setDeviceToken(value);
        return this;
    }

    @Override
    public AuthenticationLogsRecord values(UUID value1, Long value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, UUID value7, UUID value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthenticationLogsRecord
     */
    public AuthenticationLogsRecord() {
        super(AuthenticationLogs.AUTHENTİCATİON_LOGS);
    }

    /**
     * Create a detached, initialised AuthenticationLogsRecord
     */
    public AuthenticationLogsRecord(UUID uuid, Long version, String processStatus, String rowStatus, LocalDateTime createdDate, LocalDateTime modificationDate, UUID deviceUuid, UUID deviceToken) {
        super(AuthenticationLogs.AUTHENTİCATİON_LOGS);

        set(0, uuid);
        set(1, version);
        set(2, processStatus);
        set(3, rowStatus);
        set(4, createdDate);
        set(5, modificationDate);
        set(6, deviceUuid);
        set(7, deviceToken);
    }
}
