/*
 * This file is generated by jOOQ.
 */
package az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records;


import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Emails;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailsRecord extends UpdatableRecordImpl<EmailsRecord> implements Record19<UUID, Long, String, String, LocalDateTime, LocalDateTime, String, UUID, String, String, Boolean, Boolean, Boolean, String, LocalDateTime, LocalDateTime, BigDecimal, Boolean, LocalDateTime> {

    private static final long serialVersionUID = 341766056;

    /**
     * Setter for <code>auth.emails.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.emails.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>auth.emails.version</code>.
     */
    public void setVersion(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.emails.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>auth.emails.process_status</code>.
     */
    public void setProcessStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.emails.process_status</code>.
     */
    public String getProcessStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>auth.emails.row_status</code>.
     */
    public void setRowStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.emails.row_status</code>.
     */
    public String getRowStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>auth.emails.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.emails.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>auth.emails.modification_date</code>.
     */
    public void setModificationDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>auth.emails.modification_date</code>.
     */
    public LocalDateTime getModificationDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>auth.emails.access_modifier</code>.
     */
    public void setAccessModifier(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>auth.emails.access_modifier</code>.
     */
    public String getAccessModifier() {
        return (String) get(6);
    }

    /**
     * Setter for <code>auth.emails.user_uuid</code>.
     */
    public void setUserUuid(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>auth.emails.user_uuid</code>.
     */
    public UUID getUserUuid() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>auth.emails.type</code>.
     */
    public void setType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>auth.emails.type</code>.
     */
    public String getType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>auth.emails.email</code>.
     */
    public void setEmail(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>auth.emails.email</code>.
     */
    public String getEmail() {
        return (String) get(9);
    }

    /**
     * Setter for <code>auth.emails.is_enable_notification</code>.
     */
    public void setİsEnableNotification(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>auth.emails.is_enable_notification</code>.
     */
    public Boolean getİsEnableNotification() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>auth.emails.is_primary</code>.
     */
    public void setİsPrimary(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>auth.emails.is_primary</code>.
     */
    public Boolean getİsPrimary() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>auth.emails.is_verified</code>.
     */
    public void setİsVerified(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>auth.emails.is_verified</code>.
     */
    public Boolean getİsVerified() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>auth.emails.verification_code</code>.
     */
    public void setVerificationCode(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>auth.emails.verification_code</code>.
     */
    public String getVerificationCode() {
        return (String) get(13);
    }

    /**
     * Setter for <code>auth.emails.verification_code_expire_date</code>.
     */
    public void setVerificationCodeExpireDate(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>auth.emails.verification_code_expire_date</code>.
     */
    public LocalDateTime getVerificationCodeExpireDate() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>auth.emails.verification_code_send_date</code>.
     */
    public void setVerificationCodeSendDate(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>auth.emails.verification_code_send_date</code>.
     */
    public LocalDateTime getVerificationCodeSendDate() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>auth.emails.verification_code_send_count</code>.
     */
    public void setVerificationCodeSendCount(BigDecimal value) {
        set(16, value);
    }

    /**
     * Getter for <code>auth.emails.verification_code_send_count</code>.
     */
    public BigDecimal getVerificationCodeSendCount() {
        return (BigDecimal) get(16);
    }

    /**
     * Setter for <code>auth.emails.is_subscribed_promotions</code>.
     */
    public void setİsSubscribedPromotions(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>auth.emails.is_subscribed_promotions</code>.
     */
    public Boolean getİsSubscribedPromotions() {
        return (Boolean) get(17);
    }

    /**
     * Setter for <code>auth.emails.subscribed_date</code>.
     */
    public void setSubscribedDate(LocalDateTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>auth.emails.subscribed_date</code>.
     */
    public LocalDateTime getSubscribedDate() {
        return (LocalDateTime) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<UUID, Long, String, String, LocalDateTime, LocalDateTime, String, UUID, String, String, Boolean, Boolean, Boolean, String, LocalDateTime, LocalDateTime, BigDecimal, Boolean, LocalDateTime> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<UUID, Long, String, String, LocalDateTime, LocalDateTime, String, UUID, String, String, Boolean, Boolean, Boolean, String, LocalDateTime, LocalDateTime, BigDecimal, Boolean, LocalDateTime> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Emails.EMAİLS.UUİD;
    }

    @Override
    public Field<Long> field2() {
        return Emails.EMAİLS.VERSİON;
    }

    @Override
    public Field<String> field3() {
        return Emails.EMAİLS.PROCESS_STATUS;
    }

    @Override
    public Field<String> field4() {
        return Emails.EMAİLS.ROW_STATUS;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Emails.EMAİLS.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Emails.EMAİLS.MODİFİCATİON_DATE;
    }

    @Override
    public Field<String> field7() {
        return Emails.EMAİLS.ACCESS_MODİFİER;
    }

    @Override
    public Field<UUID> field8() {
        return Emails.EMAİLS.USER_UUİD;
    }

    @Override
    public Field<String> field9() {
        return Emails.EMAİLS.TYPE;
    }

    @Override
    public Field<String> field10() {
        return Emails.EMAİLS.EMAİL;
    }

    @Override
    public Field<Boolean> field11() {
        return Emails.EMAİLS.İS_ENABLE_NOTİFİCATİON;
    }

    @Override
    public Field<Boolean> field12() {
        return Emails.EMAİLS.İS_PRİMARY;
    }

    @Override
    public Field<Boolean> field13() {
        return Emails.EMAİLS.İS_VERİFİED;
    }

    @Override
    public Field<String> field14() {
        return Emails.EMAİLS.VERİFİCATİON_CODE;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return Emails.EMAİLS.VERİFİCATİON_CODE_EXPİRE_DATE;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return Emails.EMAİLS.VERİFİCATİON_CODE_SEND_DATE;
    }

    @Override
    public Field<BigDecimal> field17() {
        return Emails.EMAİLS.VERİFİCATİON_CODE_SEND_COUNT;
    }

    @Override
    public Field<Boolean> field18() {
        return Emails.EMAİLS.İS_SUBSCRİBED_PROMOTİONS;
    }

    @Override
    public Field<LocalDateTime> field19() {
        return Emails.EMAİLS.SUBSCRİBED_DATE;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public Long component2() {
        return getVersion();
    }

    @Override
    public String component3() {
        return getProcessStatus();
    }

    @Override
    public String component4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component6() {
        return getModificationDate();
    }

    @Override
    public String component7() {
        return getAccessModifier();
    }

    @Override
    public UUID component8() {
        return getUserUuid();
    }

    @Override
    public String component9() {
        return getType();
    }

    @Override
    public String component10() {
        return getEmail();
    }

    @Override
    public Boolean component11() {
        return getİsEnableNotification();
    }

    @Override
    public Boolean component12() {
        return getİsPrimary();
    }

    @Override
    public Boolean component13() {
        return getİsVerified();
    }

    @Override
    public String component14() {
        return getVerificationCode();
    }

    @Override
    public LocalDateTime component15() {
        return getVerificationCodeExpireDate();
    }

    @Override
    public LocalDateTime component16() {
        return getVerificationCodeSendDate();
    }

    @Override
    public BigDecimal component17() {
        return getVerificationCodeSendCount();
    }

    @Override
    public Boolean component18() {
        return getİsSubscribedPromotions();
    }

    @Override
    public LocalDateTime component19() {
        return getSubscribedDate();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public Long value2() {
        return getVersion();
    }

    @Override
    public String value3() {
        return getProcessStatus();
    }

    @Override
    public String value4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value6() {
        return getModificationDate();
    }

    @Override
    public String value7() {
        return getAccessModifier();
    }

    @Override
    public UUID value8() {
        return getUserUuid();
    }

    @Override
    public String value9() {
        return getType();
    }

    @Override
    public String value10() {
        return getEmail();
    }

    @Override
    public Boolean value11() {
        return getİsEnableNotification();
    }

    @Override
    public Boolean value12() {
        return getİsPrimary();
    }

    @Override
    public Boolean value13() {
        return getİsVerified();
    }

    @Override
    public String value14() {
        return getVerificationCode();
    }

    @Override
    public LocalDateTime value15() {
        return getVerificationCodeExpireDate();
    }

    @Override
    public LocalDateTime value16() {
        return getVerificationCodeSendDate();
    }

    @Override
    public BigDecimal value17() {
        return getVerificationCodeSendCount();
    }

    @Override
    public Boolean value18() {
        return getİsSubscribedPromotions();
    }

    @Override
    public LocalDateTime value19() {
        return getSubscribedDate();
    }

    @Override
    public EmailsRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public EmailsRecord value2(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public EmailsRecord value3(String value) {
        setProcessStatus(value);
        return this;
    }

    @Override
    public EmailsRecord value4(String value) {
        setRowStatus(value);
        return this;
    }

    @Override
    public EmailsRecord value5(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public EmailsRecord value6(LocalDateTime value) {
        setModificationDate(value);
        return this;
    }

    @Override
    public EmailsRecord value7(String value) {
        setAccessModifier(value);
        return this;
    }

    @Override
    public EmailsRecord value8(UUID value) {
        setUserUuid(value);
        return this;
    }

    @Override
    public EmailsRecord value9(String value) {
        setType(value);
        return this;
    }

    @Override
    public EmailsRecord value10(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public EmailsRecord value11(Boolean value) {
        setİsEnableNotification(value);
        return this;
    }

    @Override
    public EmailsRecord value12(Boolean value) {
        setİsPrimary(value);
        return this;
    }

    @Override
    public EmailsRecord value13(Boolean value) {
        setİsVerified(value);
        return this;
    }

    @Override
    public EmailsRecord value14(String value) {
        setVerificationCode(value);
        return this;
    }

    @Override
    public EmailsRecord value15(LocalDateTime value) {
        setVerificationCodeExpireDate(value);
        return this;
    }

    @Override
    public EmailsRecord value16(LocalDateTime value) {
        setVerificationCodeSendDate(value);
        return this;
    }

    @Override
    public EmailsRecord value17(BigDecimal value) {
        setVerificationCodeSendCount(value);
        return this;
    }

    @Override
    public EmailsRecord value18(Boolean value) {
        setİsSubscribedPromotions(value);
        return this;
    }

    @Override
    public EmailsRecord value19(LocalDateTime value) {
        setSubscribedDate(value);
        return this;
    }

    @Override
    public EmailsRecord values(UUID value1, Long value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, String value7, UUID value8, String value9, String value10, Boolean value11, Boolean value12, Boolean value13, String value14, LocalDateTime value15, LocalDateTime value16, BigDecimal value17, Boolean value18, LocalDateTime value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmailsRecord
     */
    public EmailsRecord() {
        super(Emails.EMAİLS);
    }

    /**
     * Create a detached, initialised EmailsRecord
     */
    public EmailsRecord(UUID uuid, Long version, String processStatus, String rowStatus, LocalDateTime createdDate, LocalDateTime modificationDate, String accessModifier, UUID userUuid, String type, String email, Boolean isEnableNotification, Boolean isPrimary, Boolean isVerified, String verificationCode, LocalDateTime verificationCodeExpireDate, LocalDateTime verificationCodeSendDate, BigDecimal verificationCodeSendCount, Boolean isSubscribedPromotions, LocalDateTime subscribedDate) {
        super(Emails.EMAİLS);

        set(0, uuid);
        set(1, version);
        set(2, processStatus);
        set(3, rowStatus);
        set(4, createdDate);
        set(5, modificationDate);
        set(6, accessModifier);
        set(7, userUuid);
        set(8, type);
        set(9, email);
        set(10, isEnableNotification);
        set(11, isPrimary);
        set(12, isVerified);
        set(13, verificationCode);
        set(14, verificationCodeExpireDate);
        set(15, verificationCodeSendDate);
        set(16, verificationCodeSendCount);
        set(17, isSubscribedPromotions);
        set(18, subscribedDate);
    }
}
