/*
 * This file is generated by jOOQ.
 */
package az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records;


import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.GeoPositions;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeoPositionsRecord extends UpdatableRecordImpl<GeoPositionsRecord> implements Record12<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, String, BigDecimal, BigDecimal, String, String> {

    private static final long serialVersionUID = 586527193;

    /**
     * Setter for <code>auth.geo_positions.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.geo_positions.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>auth.geo_positions.version</code>.
     */
    public void setVersion(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.geo_positions.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>auth.geo_positions.process_status</code>.
     */
    public void setProcessStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.geo_positions.process_status</code>.
     */
    public String getProcessStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>auth.geo_positions.row_status</code>.
     */
    public void setRowStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.geo_positions.row_status</code>.
     */
    public String getRowStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>auth.geo_positions.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.geo_positions.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>auth.geo_positions.modification_date</code>.
     */
    public void setModificationDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>auth.geo_positions.modification_date</code>.
     */
    public LocalDateTime getModificationDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>auth.geo_positions.device_entity_uuid</code>.
     */
    public void setDeviceEntityUuid(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>auth.geo_positions.device_entity_uuid</code>.
     */
    public UUID getDeviceEntityUuid() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>auth.geo_positions.country_code</code>.
     */
    public void setCountryCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>auth.geo_positions.country_code</code>.
     */
    public String getCountryCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>auth.geo_positions.latitude</code>.
     */
    public void setLatitude(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>auth.geo_positions.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>auth.geo_positions.longitude</code>.
     */
    public void setLongitude(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>auth.geo_positions.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>auth.geo_positions.timezone</code>.
     */
    public void setTimezone(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>auth.geo_positions.timezone</code>.
     */
    public String getTimezone() {
        return (String) get(10);
    }

    /**
     * Setter for <code>auth.geo_positions.gmt</code>.
     */
    public void setGmt(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>auth.geo_positions.gmt</code>.
     */
    public String getGmt() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, String, BigDecimal, BigDecimal, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, String, BigDecimal, BigDecimal, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return GeoPositions.GEO_POSİTİONS.UUİD;
    }

    @Override
    public Field<Long> field2() {
        return GeoPositions.GEO_POSİTİONS.VERSİON;
    }

    @Override
    public Field<String> field3() {
        return GeoPositions.GEO_POSİTİONS.PROCESS_STATUS;
    }

    @Override
    public Field<String> field4() {
        return GeoPositions.GEO_POSİTİONS.ROW_STATUS;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return GeoPositions.GEO_POSİTİONS.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return GeoPositions.GEO_POSİTİONS.MODİFİCATİON_DATE;
    }

    @Override
    public Field<UUID> field7() {
        return GeoPositions.GEO_POSİTİONS.DEVİCE_ENTİTY_UUİD;
    }

    @Override
    public Field<String> field8() {
        return GeoPositions.GEO_POSİTİONS.COUNTRY_CODE;
    }

    @Override
    public Field<BigDecimal> field9() {
        return GeoPositions.GEO_POSİTİONS.LATİTUDE;
    }

    @Override
    public Field<BigDecimal> field10() {
        return GeoPositions.GEO_POSİTİONS.LONGİTUDE;
    }

    @Override
    public Field<String> field11() {
        return GeoPositions.GEO_POSİTİONS.TİMEZONE;
    }

    @Override
    public Field<String> field12() {
        return GeoPositions.GEO_POSİTİONS.GMT;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public Long component2() {
        return getVersion();
    }

    @Override
    public String component3() {
        return getProcessStatus();
    }

    @Override
    public String component4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component6() {
        return getModificationDate();
    }

    @Override
    public UUID component7() {
        return getDeviceEntityUuid();
    }

    @Override
    public String component8() {
        return getCountryCode();
    }

    @Override
    public BigDecimal component9() {
        return getLatitude();
    }

    @Override
    public BigDecimal component10() {
        return getLongitude();
    }

    @Override
    public String component11() {
        return getTimezone();
    }

    @Override
    public String component12() {
        return getGmt();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public Long value2() {
        return getVersion();
    }

    @Override
    public String value3() {
        return getProcessStatus();
    }

    @Override
    public String value4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value6() {
        return getModificationDate();
    }

    @Override
    public UUID value7() {
        return getDeviceEntityUuid();
    }

    @Override
    public String value8() {
        return getCountryCode();
    }

    @Override
    public BigDecimal value9() {
        return getLatitude();
    }

    @Override
    public BigDecimal value10() {
        return getLongitude();
    }

    @Override
    public String value11() {
        return getTimezone();
    }

    @Override
    public String value12() {
        return getGmt();
    }

    @Override
    public GeoPositionsRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public GeoPositionsRecord value2(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public GeoPositionsRecord value3(String value) {
        setProcessStatus(value);
        return this;
    }

    @Override
    public GeoPositionsRecord value4(String value) {
        setRowStatus(value);
        return this;
    }

    @Override
    public GeoPositionsRecord value5(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public GeoPositionsRecord value6(LocalDateTime value) {
        setModificationDate(value);
        return this;
    }

    @Override
    public GeoPositionsRecord value7(UUID value) {
        setDeviceEntityUuid(value);
        return this;
    }

    @Override
    public GeoPositionsRecord value8(String value) {
        setCountryCode(value);
        return this;
    }

    @Override
    public GeoPositionsRecord value9(BigDecimal value) {
        setLatitude(value);
        return this;
    }

    @Override
    public GeoPositionsRecord value10(BigDecimal value) {
        setLongitude(value);
        return this;
    }

    @Override
    public GeoPositionsRecord value11(String value) {
        setTimezone(value);
        return this;
    }

    @Override
    public GeoPositionsRecord value12(String value) {
        setGmt(value);
        return this;
    }

    @Override
    public GeoPositionsRecord values(UUID value1, Long value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, UUID value7, String value8, BigDecimal value9, BigDecimal value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GeoPositionsRecord
     */
    public GeoPositionsRecord() {
        super(GeoPositions.GEO_POSİTİONS);
    }

    /**
     * Create a detached, initialised GeoPositionsRecord
     */
    public GeoPositionsRecord(UUID uuid, Long version, String processStatus, String rowStatus, LocalDateTime createdDate, LocalDateTime modificationDate, UUID deviceEntityUuid, String countryCode, BigDecimal latitude, BigDecimal longitude, String timezone, String gmt) {
        super(GeoPositions.GEO_POSİTİONS);

        set(0, uuid);
        set(1, version);
        set(2, processStatus);
        set(3, rowStatus);
        set(4, createdDate);
        set(5, modificationDate);
        set(6, deviceEntityUuid);
        set(7, countryCode);
        set(8, latitude);
        set(9, longitude);
        set(10, timezone);
        set(11, gmt);
    }
}
