/*
 * This file is generated by jOOQ.
 */
package az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records;


import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Passwords;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PasswordsRecord extends UpdatableRecordImpl<PasswordsRecord> implements Record9<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, String, String> {

    private static final long serialVersionUID = -1695325177;

    /**
     * Setter for <code>auth.passwords.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.passwords.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>auth.passwords.version</code>.
     */
    public void setVersion(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.passwords.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>auth.passwords.process_status</code>.
     */
    public void setProcessStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.passwords.process_status</code>.
     */
    public String getProcessStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>auth.passwords.row_status</code>.
     */
    public void setRowStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.passwords.row_status</code>.
     */
    public String getRowStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>auth.passwords.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.passwords.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>auth.passwords.modification_date</code>.
     */
    public void setModificationDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>auth.passwords.modification_date</code>.
     */
    public LocalDateTime getModificationDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>auth.passwords.user_uuid</code>.
     */
    public void setUserUuid(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>auth.passwords.user_uuid</code>.
     */
    public UUID getUserUuid() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>auth.passwords.salt</code>.
     */
    public void setSalt(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>auth.passwords.salt</code>.
     */
    public String getSalt() {
        return (String) get(7);
    }

    /**
     * Setter for <code>auth.passwords.hash</code>.
     */
    public void setHash(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>auth.passwords.hash</code>.
     */
    public String getHash() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Passwords.PASSWORDS.UUİD;
    }

    @Override
    public Field<Long> field2() {
        return Passwords.PASSWORDS.VERSİON;
    }

    @Override
    public Field<String> field3() {
        return Passwords.PASSWORDS.PROCESS_STATUS;
    }

    @Override
    public Field<String> field4() {
        return Passwords.PASSWORDS.ROW_STATUS;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Passwords.PASSWORDS.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Passwords.PASSWORDS.MODİFİCATİON_DATE;
    }

    @Override
    public Field<UUID> field7() {
        return Passwords.PASSWORDS.USER_UUİD;
    }

    @Override
    public Field<String> field8() {
        return Passwords.PASSWORDS.SALT;
    }

    @Override
    public Field<String> field9() {
        return Passwords.PASSWORDS.HASH;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public Long component2() {
        return getVersion();
    }

    @Override
    public String component3() {
        return getProcessStatus();
    }

    @Override
    public String component4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component6() {
        return getModificationDate();
    }

    @Override
    public UUID component7() {
        return getUserUuid();
    }

    @Override
    public String component8() {
        return getSalt();
    }

    @Override
    public String component9() {
        return getHash();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public Long value2() {
        return getVersion();
    }

    @Override
    public String value3() {
        return getProcessStatus();
    }

    @Override
    public String value4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value6() {
        return getModificationDate();
    }

    @Override
    public UUID value7() {
        return getUserUuid();
    }

    @Override
    public String value8() {
        return getSalt();
    }

    @Override
    public String value9() {
        return getHash();
    }

    @Override
    public PasswordsRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public PasswordsRecord value2(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public PasswordsRecord value3(String value) {
        setProcessStatus(value);
        return this;
    }

    @Override
    public PasswordsRecord value4(String value) {
        setRowStatus(value);
        return this;
    }

    @Override
    public PasswordsRecord value5(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public PasswordsRecord value6(LocalDateTime value) {
        setModificationDate(value);
        return this;
    }

    @Override
    public PasswordsRecord value7(UUID value) {
        setUserUuid(value);
        return this;
    }

    @Override
    public PasswordsRecord value8(String value) {
        setSalt(value);
        return this;
    }

    @Override
    public PasswordsRecord value9(String value) {
        setHash(value);
        return this;
    }

    @Override
    public PasswordsRecord values(UUID value1, Long value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, UUID value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PasswordsRecord
     */
    public PasswordsRecord() {
        super(Passwords.PASSWORDS);
    }

    /**
     * Create a detached, initialised PasswordsRecord
     */
    public PasswordsRecord(UUID uuid, Long version, String processStatus, String rowStatus, LocalDateTime createdDate, LocalDateTime modificationDate, UUID userUuid, String salt, String hash) {
        super(Passwords.PASSWORDS);

        set(0, uuid);
        set(1, version);
        set(2, processStatus);
        set(3, rowStatus);
        set(4, createdDate);
        set(5, modificationDate);
        set(6, userUuid);
        set(7, salt);
        set(8, hash);
    }
}
