/*
 * This file is generated by jOOQ.
 */
package az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records;


import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.PhoneNumbers;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PhoneNumbersRecord extends UpdatableRecordImpl<PhoneNumbersRecord> implements Record19<UUID, Long, String, String, LocalDateTime, LocalDateTime, String, UUID, String, String, String, Boolean, Boolean, Boolean, Boolean, String, LocalDateTime, LocalDateTime, BigDecimal> {

    private static final long serialVersionUID = -713753469;

    /**
     * Setter for <code>auth.phone_numbers.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>auth.phone_numbers.version</code>.
     */
    public void setVersion(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>auth.phone_numbers.process_status</code>.
     */
    public void setProcessStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.process_status</code>.
     */
    public String getProcessStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>auth.phone_numbers.row_status</code>.
     */
    public void setRowStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.row_status</code>.
     */
    public String getRowStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>auth.phone_numbers.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>auth.phone_numbers.modification_date</code>.
     */
    public void setModificationDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.modification_date</code>.
     */
    public LocalDateTime getModificationDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>auth.phone_numbers.access_modifier</code>.
     */
    public void setAccessModifier(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.access_modifier</code>.
     */
    public String getAccessModifier() {
        return (String) get(6);
    }

    /**
     * Setter for <code>auth.phone_numbers.user_uuid</code>.
     */
    public void setUserUuid(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.user_uuid</code>.
     */
    public UUID getUserUuid() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>auth.phone_numbers.country_code</code>.
     */
    public void setCountryCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.country_code</code>.
     */
    public String getCountryCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>auth.phone_numbers.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(9);
    }

    /**
     * Setter for <code>auth.phone_numbers.type</code>.
     */
    public void setType(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.type</code>.
     */
    public String getType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>auth.phone_numbers.is_enable_sms_notification</code>.
     */
    public void setİsEnableSmsNotification(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.is_enable_sms_notification</code>.
     */
    public Boolean getİsEnableSmsNotification() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>auth.phone_numbers.is_enable_whatsapp_notification</code>.
     */
    public void setİsEnableWhatsappNotification(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.is_enable_whatsapp_notification</code>.
     */
    public Boolean getİsEnableWhatsappNotification() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>auth.phone_numbers.is_primary</code>.
     */
    public void setİsPrimary(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.is_primary</code>.
     */
    public Boolean getİsPrimary() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>auth.phone_numbers.is_verified</code>.
     */
    public void setİsVerified(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.is_verified</code>.
     */
    public Boolean getİsVerified() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>auth.phone_numbers.verification_code</code>.
     */
    public void setVerificationCode(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.verification_code</code>.
     */
    public String getVerificationCode() {
        return (String) get(15);
    }

    /**
     * Setter for <code>auth.phone_numbers.verification_code_expire_date</code>.
     */
    public void setVerificationCodeExpireDate(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.verification_code_expire_date</code>.
     */
    public LocalDateTime getVerificationCodeExpireDate() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>auth.phone_numbers.verification_code_send_date</code>.
     */
    public void setVerificationCodeSendDate(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.verification_code_send_date</code>.
     */
    public LocalDateTime getVerificationCodeSendDate() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>auth.phone_numbers.verification_code_send_count</code>.
     */
    public void setVerificationCodeSendCount(BigDecimal value) {
        set(18, value);
    }

    /**
     * Getter for <code>auth.phone_numbers.verification_code_send_count</code>.
     */
    public BigDecimal getVerificationCodeSendCount() {
        return (BigDecimal) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<UUID, Long, String, String, LocalDateTime, LocalDateTime, String, UUID, String, String, String, Boolean, Boolean, Boolean, Boolean, String, LocalDateTime, LocalDateTime, BigDecimal> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<UUID, Long, String, String, LocalDateTime, LocalDateTime, String, UUID, String, String, String, Boolean, Boolean, Boolean, Boolean, String, LocalDateTime, LocalDateTime, BigDecimal> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return PhoneNumbers.PHONE_NUMBERS.UUİD;
    }

    @Override
    public Field<Long> field2() {
        return PhoneNumbers.PHONE_NUMBERS.VERSİON;
    }

    @Override
    public Field<String> field3() {
        return PhoneNumbers.PHONE_NUMBERS.PROCESS_STATUS;
    }

    @Override
    public Field<String> field4() {
        return PhoneNumbers.PHONE_NUMBERS.ROW_STATUS;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return PhoneNumbers.PHONE_NUMBERS.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return PhoneNumbers.PHONE_NUMBERS.MODİFİCATİON_DATE;
    }

    @Override
    public Field<String> field7() {
        return PhoneNumbers.PHONE_NUMBERS.ACCESS_MODİFİER;
    }

    @Override
    public Field<UUID> field8() {
        return PhoneNumbers.PHONE_NUMBERS.USER_UUİD;
    }

    @Override
    public Field<String> field9() {
        return PhoneNumbers.PHONE_NUMBERS.COUNTRY_CODE;
    }

    @Override
    public Field<String> field10() {
        return PhoneNumbers.PHONE_NUMBERS.PHONE_NUMBER;
    }

    @Override
    public Field<String> field11() {
        return PhoneNumbers.PHONE_NUMBERS.TYPE;
    }

    @Override
    public Field<Boolean> field12() {
        return PhoneNumbers.PHONE_NUMBERS.İS_ENABLE_SMS_NOTİFİCATİON;
    }

    @Override
    public Field<Boolean> field13() {
        return PhoneNumbers.PHONE_NUMBERS.İS_ENABLE_WHATSAPP_NOTİFİCATİON;
    }

    @Override
    public Field<Boolean> field14() {
        return PhoneNumbers.PHONE_NUMBERS.İS_PRİMARY;
    }

    @Override
    public Field<Boolean> field15() {
        return PhoneNumbers.PHONE_NUMBERS.İS_VERİFİED;
    }

    @Override
    public Field<String> field16() {
        return PhoneNumbers.PHONE_NUMBERS.VERİFİCATİON_CODE;
    }

    @Override
    public Field<LocalDateTime> field17() {
        return PhoneNumbers.PHONE_NUMBERS.VERİFİCATİON_CODE_EXPİRE_DATE;
    }

    @Override
    public Field<LocalDateTime> field18() {
        return PhoneNumbers.PHONE_NUMBERS.VERİFİCATİON_CODE_SEND_DATE;
    }

    @Override
    public Field<BigDecimal> field19() {
        return PhoneNumbers.PHONE_NUMBERS.VERİFİCATİON_CODE_SEND_COUNT;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public Long component2() {
        return getVersion();
    }

    @Override
    public String component3() {
        return getProcessStatus();
    }

    @Override
    public String component4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component6() {
        return getModificationDate();
    }

    @Override
    public String component7() {
        return getAccessModifier();
    }

    @Override
    public UUID component8() {
        return getUserUuid();
    }

    @Override
    public String component9() {
        return getCountryCode();
    }

    @Override
    public String component10() {
        return getPhoneNumber();
    }

    @Override
    public String component11() {
        return getType();
    }

    @Override
    public Boolean component12() {
        return getİsEnableSmsNotification();
    }

    @Override
    public Boolean component13() {
        return getİsEnableWhatsappNotification();
    }

    @Override
    public Boolean component14() {
        return getİsPrimary();
    }

    @Override
    public Boolean component15() {
        return getİsVerified();
    }

    @Override
    public String component16() {
        return getVerificationCode();
    }

    @Override
    public LocalDateTime component17() {
        return getVerificationCodeExpireDate();
    }

    @Override
    public LocalDateTime component18() {
        return getVerificationCodeSendDate();
    }

    @Override
    public BigDecimal component19() {
        return getVerificationCodeSendCount();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public Long value2() {
        return getVersion();
    }

    @Override
    public String value3() {
        return getProcessStatus();
    }

    @Override
    public String value4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value6() {
        return getModificationDate();
    }

    @Override
    public String value7() {
        return getAccessModifier();
    }

    @Override
    public UUID value8() {
        return getUserUuid();
    }

    @Override
    public String value9() {
        return getCountryCode();
    }

    @Override
    public String value10() {
        return getPhoneNumber();
    }

    @Override
    public String value11() {
        return getType();
    }

    @Override
    public Boolean value12() {
        return getİsEnableSmsNotification();
    }

    @Override
    public Boolean value13() {
        return getİsEnableWhatsappNotification();
    }

    @Override
    public Boolean value14() {
        return getİsPrimary();
    }

    @Override
    public Boolean value15() {
        return getİsVerified();
    }

    @Override
    public String value16() {
        return getVerificationCode();
    }

    @Override
    public LocalDateTime value17() {
        return getVerificationCodeExpireDate();
    }

    @Override
    public LocalDateTime value18() {
        return getVerificationCodeSendDate();
    }

    @Override
    public BigDecimal value19() {
        return getVerificationCodeSendCount();
    }

    @Override
    public PhoneNumbersRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value2(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value3(String value) {
        setProcessStatus(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value4(String value) {
        setRowStatus(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value5(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value6(LocalDateTime value) {
        setModificationDate(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value7(String value) {
        setAccessModifier(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value8(UUID value) {
        setUserUuid(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value9(String value) {
        setCountryCode(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value10(String value) {
        setPhoneNumber(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value11(String value) {
        setType(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value12(Boolean value) {
        setİsEnableSmsNotification(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value13(Boolean value) {
        setİsEnableWhatsappNotification(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value14(Boolean value) {
        setİsPrimary(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value15(Boolean value) {
        setİsVerified(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value16(String value) {
        setVerificationCode(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value17(LocalDateTime value) {
        setVerificationCodeExpireDate(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value18(LocalDateTime value) {
        setVerificationCodeSendDate(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord value19(BigDecimal value) {
        setVerificationCodeSendCount(value);
        return this;
    }

    @Override
    public PhoneNumbersRecord values(UUID value1, Long value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, String value7, UUID value8, String value9, String value10, String value11, Boolean value12, Boolean value13, Boolean value14, Boolean value15, String value16, LocalDateTime value17, LocalDateTime value18, BigDecimal value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PhoneNumbersRecord
     */
    public PhoneNumbersRecord() {
        super(PhoneNumbers.PHONE_NUMBERS);
    }

    /**
     * Create a detached, initialised PhoneNumbersRecord
     */
    public PhoneNumbersRecord(UUID uuid, Long version, String processStatus, String rowStatus, LocalDateTime createdDate, LocalDateTime modificationDate, String accessModifier, UUID userUuid, String countryCode, String phoneNumber, String type, Boolean isEnableSmsNotification, Boolean isEnableWhatsappNotification, Boolean isPrimary, Boolean isVerified, String verificationCode, LocalDateTime verificationCodeExpireDate, LocalDateTime verificationCodeSendDate, BigDecimal verificationCodeSendCount) {
        super(PhoneNumbers.PHONE_NUMBERS);

        set(0, uuid);
        set(1, version);
        set(2, processStatus);
        set(3, rowStatus);
        set(4, createdDate);
        set(5, modificationDate);
        set(6, accessModifier);
        set(7, userUuid);
        set(8, countryCode);
        set(9, phoneNumber);
        set(10, type);
        set(11, isEnableSmsNotification);
        set(12, isEnableWhatsappNotification);
        set(13, isPrimary);
        set(14, isVerified);
        set(15, verificationCode);
        set(16, verificationCodeExpireDate);
        set(17, verificationCodeSendDate);
        set(18, verificationCodeSendCount);
    }
}
