/*
 * This file is generated by jOOQ.
 */
package az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records;


import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.ProfilePictures;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfilePicturesRecord extends UpdatableRecordImpl<ProfilePicturesRecord> implements Record19<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, String, Boolean, String, String, String, String, Long, String, String, String, String, String> {

    private static final long serialVersionUID = -187859934;

    /**
     * Setter for <code>auth.profile_pictures.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>auth.profile_pictures.version</code>.
     */
    public void setVersion(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>auth.profile_pictures.process_status</code>.
     */
    public void setProcessStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.process_status</code>.
     */
    public String getProcessStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>auth.profile_pictures.row_status</code>.
     */
    public void setRowStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.row_status</code>.
     */
    public String getRowStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>auth.profile_pictures.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>auth.profile_pictures.modification_date</code>.
     */
    public void setModificationDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.modification_date</code>.
     */
    public LocalDateTime getModificationDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>auth.profile_pictures.user_uuid</code>.
     */
    public void setUserUuid(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.user_uuid</code>.
     */
    public UUID getUserUuid() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>auth.profile_pictures.access_modifier</code>.
     */
    public void setAccessModifier(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.access_modifier</code>.
     */
    public String getAccessModifier() {
        return (String) get(7);
    }

    /**
     * Setter for <code>auth.profile_pictures.is_current</code>.
     */
    public void setİsCurrent(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.is_current</code>.
     */
    public Boolean getİsCurrent() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>auth.profile_pictures.region</code>.
     */
    public void setRegion(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.region</code>.
     */
    public String getRegion() {
        return (String) get(9);
    }

    /**
     * Setter for <code>auth.profile_pictures.file_path</code>.
     */
    public void setFilePath(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.file_path</code>.
     */
    public String getFilePath() {
        return (String) get(10);
    }

    /**
     * Setter for <code>auth.profile_pictures.file_name</code>.
     */
    public void setFileName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.file_name</code>.
     */
    public String getFileName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>auth.profile_pictures.file_format</code>.
     */
    public void setFileFormat(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.file_format</code>.
     */
    public String getFileFormat() {
        return (String) get(12);
    }

    /**
     * Setter for <code>auth.profile_pictures.file_size</code>.
     */
    public void setFileSize(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.file_size</code>.
     */
    public Long getFileSize() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>auth.profile_pictures.file_url_thumbnail</code>.
     */
    public void setFileUrlThumbnail(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.file_url_thumbnail</code>.
     */
    public String getFileUrlThumbnail() {
        return (String) get(14);
    }

    /**
     * Setter for <code>auth.profile_pictures.file_url_small</code>.
     */
    public void setFileUrlSmall(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.file_url_small</code>.
     */
    public String getFileUrlSmall() {
        return (String) get(15);
    }

    /**
     * Setter for <code>auth.profile_pictures.file_url_medium</code>.
     */
    public void setFileUrlMedium(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.file_url_medium</code>.
     */
    public String getFileUrlMedium() {
        return (String) get(16);
    }

    /**
     * Setter for <code>auth.profile_pictures.file_url_large</code>.
     */
    public void setFileUrlLarge(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.file_url_large</code>.
     */
    public String getFileUrlLarge() {
        return (String) get(17);
    }

    /**
     * Setter for <code>auth.profile_pictures.file_url_webp</code>.
     */
    public void setFileUrlWebp(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>auth.profile_pictures.file_url_webp</code>.
     */
    public String getFileUrlWebp() {
        return (String) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, String, Boolean, String, String, String, String, Long, String, String, String, String, String> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, String, Boolean, String, String, String, String, Long, String, String, String, String, String> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return ProfilePictures.PROFİLE_PİCTURES.UUİD;
    }

    @Override
    public Field<Long> field2() {
        return ProfilePictures.PROFİLE_PİCTURES.VERSİON;
    }

    @Override
    public Field<String> field3() {
        return ProfilePictures.PROFİLE_PİCTURES.PROCESS_STATUS;
    }

    @Override
    public Field<String> field4() {
        return ProfilePictures.PROFİLE_PİCTURES.ROW_STATUS;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ProfilePictures.PROFİLE_PİCTURES.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return ProfilePictures.PROFİLE_PİCTURES.MODİFİCATİON_DATE;
    }

    @Override
    public Field<UUID> field7() {
        return ProfilePictures.PROFİLE_PİCTURES.USER_UUİD;
    }

    @Override
    public Field<String> field8() {
        return ProfilePictures.PROFİLE_PİCTURES.ACCESS_MODİFİER;
    }

    @Override
    public Field<Boolean> field9() {
        return ProfilePictures.PROFİLE_PİCTURES.İS_CURRENT;
    }

    @Override
    public Field<String> field10() {
        return ProfilePictures.PROFİLE_PİCTURES.REGİON;
    }

    @Override
    public Field<String> field11() {
        return ProfilePictures.PROFİLE_PİCTURES.FİLE_PATH;
    }

    @Override
    public Field<String> field12() {
        return ProfilePictures.PROFİLE_PİCTURES.FİLE_NAME;
    }

    @Override
    public Field<String> field13() {
        return ProfilePictures.PROFİLE_PİCTURES.FİLE_FORMAT;
    }

    @Override
    public Field<Long> field14() {
        return ProfilePictures.PROFİLE_PİCTURES.FİLE_SİZE;
    }

    @Override
    public Field<String> field15() {
        return ProfilePictures.PROFİLE_PİCTURES.FİLE_URL_THUMBNAİL;
    }

    @Override
    public Field<String> field16() {
        return ProfilePictures.PROFİLE_PİCTURES.FİLE_URL_SMALL;
    }

    @Override
    public Field<String> field17() {
        return ProfilePictures.PROFİLE_PİCTURES.FİLE_URL_MEDİUM;
    }

    @Override
    public Field<String> field18() {
        return ProfilePictures.PROFİLE_PİCTURES.FİLE_URL_LARGE;
    }

    @Override
    public Field<String> field19() {
        return ProfilePictures.PROFİLE_PİCTURES.FİLE_URL_WEBP;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public Long component2() {
        return getVersion();
    }

    @Override
    public String component3() {
        return getProcessStatus();
    }

    @Override
    public String component4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component6() {
        return getModificationDate();
    }

    @Override
    public UUID component7() {
        return getUserUuid();
    }

    @Override
    public String component8() {
        return getAccessModifier();
    }

    @Override
    public Boolean component9() {
        return getİsCurrent();
    }

    @Override
    public String component10() {
        return getRegion();
    }

    @Override
    public String component11() {
        return getFilePath();
    }

    @Override
    public String component12() {
        return getFileName();
    }

    @Override
    public String component13() {
        return getFileFormat();
    }

    @Override
    public Long component14() {
        return getFileSize();
    }

    @Override
    public String component15() {
        return getFileUrlThumbnail();
    }

    @Override
    public String component16() {
        return getFileUrlSmall();
    }

    @Override
    public String component17() {
        return getFileUrlMedium();
    }

    @Override
    public String component18() {
        return getFileUrlLarge();
    }

    @Override
    public String component19() {
        return getFileUrlWebp();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public Long value2() {
        return getVersion();
    }

    @Override
    public String value3() {
        return getProcessStatus();
    }

    @Override
    public String value4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value6() {
        return getModificationDate();
    }

    @Override
    public UUID value7() {
        return getUserUuid();
    }

    @Override
    public String value8() {
        return getAccessModifier();
    }

    @Override
    public Boolean value9() {
        return getİsCurrent();
    }

    @Override
    public String value10() {
        return getRegion();
    }

    @Override
    public String value11() {
        return getFilePath();
    }

    @Override
    public String value12() {
        return getFileName();
    }

    @Override
    public String value13() {
        return getFileFormat();
    }

    @Override
    public Long value14() {
        return getFileSize();
    }

    @Override
    public String value15() {
        return getFileUrlThumbnail();
    }

    @Override
    public String value16() {
        return getFileUrlSmall();
    }

    @Override
    public String value17() {
        return getFileUrlMedium();
    }

    @Override
    public String value18() {
        return getFileUrlLarge();
    }

    @Override
    public String value19() {
        return getFileUrlWebp();
    }

    @Override
    public ProfilePicturesRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value2(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value3(String value) {
        setProcessStatus(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value4(String value) {
        setRowStatus(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value5(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value6(LocalDateTime value) {
        setModificationDate(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value7(UUID value) {
        setUserUuid(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value8(String value) {
        setAccessModifier(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value9(Boolean value) {
        setİsCurrent(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value10(String value) {
        setRegion(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value11(String value) {
        setFilePath(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value12(String value) {
        setFileName(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value13(String value) {
        setFileFormat(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value14(Long value) {
        setFileSize(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value15(String value) {
        setFileUrlThumbnail(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value16(String value) {
        setFileUrlSmall(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value17(String value) {
        setFileUrlMedium(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value18(String value) {
        setFileUrlLarge(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord value19(String value) {
        setFileUrlWebp(value);
        return this;
    }

    @Override
    public ProfilePicturesRecord values(UUID value1, Long value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, UUID value7, String value8, Boolean value9, String value10, String value11, String value12, String value13, Long value14, String value15, String value16, String value17, String value18, String value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProfilePicturesRecord
     */
    public ProfilePicturesRecord() {
        super(ProfilePictures.PROFİLE_PİCTURES);
    }

    /**
     * Create a detached, initialised ProfilePicturesRecord
     */
    public ProfilePicturesRecord(UUID uuid, Long version, String processStatus, String rowStatus, LocalDateTime createdDate, LocalDateTime modificationDate, UUID userUuid, String accessModifier, Boolean isCurrent, String region, String filePath, String fileName, String fileFormat, Long fileSize, String fileUrlThumbnail, String fileUrlSmall, String fileUrlMedium, String fileUrlLarge, String fileUrlWebp) {
        super(ProfilePictures.PROFİLE_PİCTURES);

        set(0, uuid);
        set(1, version);
        set(2, processStatus);
        set(3, rowStatus);
        set(4, createdDate);
        set(5, modificationDate);
        set(6, userUuid);
        set(7, accessModifier);
        set(8, isCurrent);
        set(9, region);
        set(10, filePath);
        set(11, fileName);
        set(12, fileFormat);
        set(13, fileSize);
        set(14, fileUrlThumbnail);
        set(15, fileUrlSmall);
        set(16, fileUrlMedium);
        set(17, fileUrlLarge);
        set(18, fileUrlWebp);
    }
}
