/*
 * This file is generated by jOOQ.
 */
package az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records;


import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.Users;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record14<UUID, Long, String, String, LocalDateTime, LocalDateTime, String, String, UUID, String, String, String, String, String> {

    private static final long serialVersionUID = -802288919;

    /**
     * Setter for <code>auth.users.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.users.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>auth.users.version</code>.
     */
    public void setVersion(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.users.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>auth.users.process_status</code>.
     */
    public void setProcessStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.users.process_status</code>.
     */
    public String getProcessStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>auth.users.row_status</code>.
     */
    public void setRowStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.users.row_status</code>.
     */
    public String getRowStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>auth.users.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.users.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>auth.users.modification_date</code>.
     */
    public void setModificationDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>auth.users.modification_date</code>.
     */
    public LocalDateTime getModificationDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>auth.users.access_modifier</code>.
     */
    public void setAccessModifier(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>auth.users.access_modifier</code>.
     */
    public String getAccessModifier() {
        return (String) get(6);
    }

    /**
     * Setter for <code>auth.users.user_type</code>.
     */
    public void setUserType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>auth.users.user_type</code>.
     */
    public String getUserType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>auth.users.key</code>.
     */
    public void setKey(UUID value) {
        set(8, value);
    }

    /**
     * Getter for <code>auth.users.key</code>.
     */
    public UUID getKey() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>auth.users.first_name</code>.
     */
    public void setFirstName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>auth.users.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>auth.users.last_name</code>.
     */
    public void setLastName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>auth.users.last_name</code>.
     */
    public String getLastName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>auth.users.username</code>.
     */
    public void setUsername(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>auth.users.username</code>.
     */
    public String getUsername() {
        return (String) get(11);
    }

    /**
     * Setter for <code>auth.users.timezone</code>.
     */
    public void setTimezone(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>auth.users.timezone</code>.
     */
    public String getTimezone() {
        return (String) get(12);
    }

    /**
     * Setter for <code>auth.users.gender</code>.
     */
    public void setGender(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>auth.users.gender</code>.
     */
    public String getGender() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<UUID, Long, String, String, LocalDateTime, LocalDateTime, String, String, UUID, String, String, String, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<UUID, Long, String, String, LocalDateTime, LocalDateTime, String, String, UUID, String, String, String, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Users.USERS.UUİD;
    }

    @Override
    public Field<Long> field2() {
        return Users.USERS.VERSİON;
    }

    @Override
    public Field<String> field3() {
        return Users.USERS.PROCESS_STATUS;
    }

    @Override
    public Field<String> field4() {
        return Users.USERS.ROW_STATUS;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Users.USERS.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Users.USERS.MODİFİCATİON_DATE;
    }

    @Override
    public Field<String> field7() {
        return Users.USERS.ACCESS_MODİFİER;
    }

    @Override
    public Field<String> field8() {
        return Users.USERS.USER_TYPE;
    }

    @Override
    public Field<UUID> field9() {
        return Users.USERS.KEY;
    }

    @Override
    public Field<String> field10() {
        return Users.USERS.FİRST_NAME;
    }

    @Override
    public Field<String> field11() {
        return Users.USERS.LAST_NAME;
    }

    @Override
    public Field<String> field12() {
        return Users.USERS.USERNAME;
    }

    @Override
    public Field<String> field13() {
        return Users.USERS.TİMEZONE;
    }

    @Override
    public Field<String> field14() {
        return Users.USERS.GENDER;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public Long component2() {
        return getVersion();
    }

    @Override
    public String component3() {
        return getProcessStatus();
    }

    @Override
    public String component4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component6() {
        return getModificationDate();
    }

    @Override
    public String component7() {
        return getAccessModifier();
    }

    @Override
    public String component8() {
        return getUserType();
    }

    @Override
    public UUID component9() {
        return getKey();
    }

    @Override
    public String component10() {
        return getFirstName();
    }

    @Override
    public String component11() {
        return getLastName();
    }

    @Override
    public String component12() {
        return getUsername();
    }

    @Override
    public String component13() {
        return getTimezone();
    }

    @Override
    public String component14() {
        return getGender();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public Long value2() {
        return getVersion();
    }

    @Override
    public String value3() {
        return getProcessStatus();
    }

    @Override
    public String value4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value6() {
        return getModificationDate();
    }

    @Override
    public String value7() {
        return getAccessModifier();
    }

    @Override
    public String value8() {
        return getUserType();
    }

    @Override
    public UUID value9() {
        return getKey();
    }

    @Override
    public String value10() {
        return getFirstName();
    }

    @Override
    public String value11() {
        return getLastName();
    }

    @Override
    public String value12() {
        return getUsername();
    }

    @Override
    public String value13() {
        return getTimezone();
    }

    @Override
    public String value14() {
        return getGender();
    }

    @Override
    public UsersRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public UsersRecord value2(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public UsersRecord value3(String value) {
        setProcessStatus(value);
        return this;
    }

    @Override
    public UsersRecord value4(String value) {
        setRowStatus(value);
        return this;
    }

    @Override
    public UsersRecord value5(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public UsersRecord value6(LocalDateTime value) {
        setModificationDate(value);
        return this;
    }

    @Override
    public UsersRecord value7(String value) {
        setAccessModifier(value);
        return this;
    }

    @Override
    public UsersRecord value8(String value) {
        setUserType(value);
        return this;
    }

    @Override
    public UsersRecord value9(UUID value) {
        setKey(value);
        return this;
    }

    @Override
    public UsersRecord value10(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public UsersRecord value11(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public UsersRecord value12(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UsersRecord value13(String value) {
        setTimezone(value);
        return this;
    }

    @Override
    public UsersRecord value14(String value) {
        setGender(value);
        return this;
    }

    @Override
    public UsersRecord values(UUID value1, Long value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, String value7, String value8, UUID value9, String value10, String value11, String value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(UUID uuid, Long version, String processStatus, String rowStatus, LocalDateTime createdDate, LocalDateTime modificationDate, String accessModifier, String userType, UUID key, String firstName, String lastName, String username, String timezone, String gender) {
        super(Users.USERS);

        set(0, uuid);
        set(1, version);
        set(2, processStatus);
        set(3, rowStatus);
        set(4, createdDate);
        set(5, modificationDate);
        set(6, accessModifier);
        set(7, userType);
        set(8, key);
        set(9, firstName);
        set(10, lastName);
        set(11, username);
        set(12, timezone);
        set(13, gender);
    }
}
