/*
 * This file is generated by jOOQ.
 */
package az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.records;


import az.rock.flyjob.auth.dataAccess.model.jooq.auth.tables.UserSettings;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSettingsRecord extends UpdatableRecordImpl<UserSettingsRecord> implements Record19<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, String, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean> {

    private static final long serialVersionUID = -1276707551;

    /**
     * Setter for <code>auth.user_settings.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.user_settings.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>auth.user_settings.version</code>.
     */
    public void setVersion(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.user_settings.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>auth.user_settings.process_status</code>.
     */
    public void setProcessStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.user_settings.process_status</code>.
     */
    public String getProcessStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>auth.user_settings.row_status</code>.
     */
    public void setRowStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.user_settings.row_status</code>.
     */
    public String getRowStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>auth.user_settings.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.user_settings.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>auth.user_settings.modification_date</code>.
     */
    public void setModificationDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>auth.user_settings.modification_date</code>.
     */
    public LocalDateTime getModificationDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>auth.user_settings.user_uuid</code>.
     */
    public void setUserUuid(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>auth.user_settings.user_uuid</code>.
     */
    public UUID getUserUuid() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>auth.user_settings.language</code>.
     */
    public void setLanguage(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>auth.user_settings.language</code>.
     */
    public String getLanguage() {
        return (String) get(7);
    }

    /**
     * Setter for <code>auth.user_settings.is_active_dark_mode</code>.
     */
    public void setİsActiveDarkMode(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>auth.user_settings.is_active_dark_mode</code>.
     */
    public Boolean getİsActiveDarkMode() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>auth.user_settings.is_active_email_notification</code>.
     */
    public void setİsActiveEmailNotification(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>auth.user_settings.is_active_email_notification</code>.
     */
    public Boolean getİsActiveEmailNotification() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>auth.user_settings.is_active_sms_notification</code>.
     */
    public void setİsActiveSmsNotification(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>auth.user_settings.is_active_sms_notification</code>.
     */
    public Boolean getİsActiveSmsNotification() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>auth.user_settings.is_active_push_notification</code>.
     */
    public void setİsActivePushNotification(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>auth.user_settings.is_active_push_notification</code>.
     */
    public Boolean getİsActivePushNotification() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>auth.user_settings.is_active_two_factor_authentication</code>.
     */
    public void setİsActiveTwoFactorAuthentication(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>auth.user_settings.is_active_two_factor_authentication</code>.
     */
    public Boolean getİsActiveTwoFactorAuthentication() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>auth.user_settings.is_visible_location</code>.
     */
    public void setİsVisibleLocation(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>auth.user_settings.is_visible_location</code>.
     */
    public Boolean getİsVisibleLocation() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>auth.user_settings.is_visible_online_status</code>.
     */
    public void setİsVisibleOnlineStatus(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>auth.user_settings.is_visible_online_status</code>.
     */
    public Boolean getİsVisibleOnlineStatus() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>auth.user_settings.is_visible_last_seen</code>.
     */
    public void setİsVisibleLastSeen(Boolean value) {
        set(15, value);
    }

    /**
     * Getter for <code>auth.user_settings.is_visible_last_seen</code>.
     */
    public Boolean getİsVisibleLastSeen() {
        return (Boolean) get(15);
    }

    /**
     * Setter for <code>auth.user_settings.is_visible_profile_picture</code>.
     */
    public void setİsVisibleProfilePicture(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>auth.user_settings.is_visible_profile_picture</code>.
     */
    public Boolean getİsVisibleProfilePicture() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>auth.user_settings.is_visible_email</code>.
     */
    public void setİsVisibleEmail(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>auth.user_settings.is_visible_email</code>.
     */
    public Boolean getİsVisibleEmail() {
        return (Boolean) get(17);
    }

    /**
     * Setter for <code>auth.user_settings.is_visible_resume</code>.
     */
    public void setİsVisibleResume(Boolean value) {
        set(18, value);
    }

    /**
     * Getter for <code>auth.user_settings.is_visible_resume</code>.
     */
    public Boolean getİsVisibleResume() {
        return (Boolean) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, String, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<UUID, Long, String, String, LocalDateTime, LocalDateTime, UUID, String, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return UserSettings.USER_SETTİNGS.UUİD;
    }

    @Override
    public Field<Long> field2() {
        return UserSettings.USER_SETTİNGS.VERSİON;
    }

    @Override
    public Field<String> field3() {
        return UserSettings.USER_SETTİNGS.PROCESS_STATUS;
    }

    @Override
    public Field<String> field4() {
        return UserSettings.USER_SETTİNGS.ROW_STATUS;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return UserSettings.USER_SETTİNGS.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return UserSettings.USER_SETTİNGS.MODİFİCATİON_DATE;
    }

    @Override
    public Field<UUID> field7() {
        return UserSettings.USER_SETTİNGS.USER_UUİD;
    }

    @Override
    public Field<String> field8() {
        return UserSettings.USER_SETTİNGS.LANGUAGE;
    }

    @Override
    public Field<Boolean> field9() {
        return UserSettings.USER_SETTİNGS.İS_ACTİVE_DARK_MODE;
    }

    @Override
    public Field<Boolean> field10() {
        return UserSettings.USER_SETTİNGS.İS_ACTİVE_EMAİL_NOTİFİCATİON;
    }

    @Override
    public Field<Boolean> field11() {
        return UserSettings.USER_SETTİNGS.İS_ACTİVE_SMS_NOTİFİCATİON;
    }

    @Override
    public Field<Boolean> field12() {
        return UserSettings.USER_SETTİNGS.İS_ACTİVE_PUSH_NOTİFİCATİON;
    }

    @Override
    public Field<Boolean> field13() {
        return UserSettings.USER_SETTİNGS.İS_ACTİVE_TWO_FACTOR_AUTHENTİCATİON;
    }

    @Override
    public Field<Boolean> field14() {
        return UserSettings.USER_SETTİNGS.İS_VİSİBLE_LOCATİON;
    }

    @Override
    public Field<Boolean> field15() {
        return UserSettings.USER_SETTİNGS.İS_VİSİBLE_ONLİNE_STATUS;
    }

    @Override
    public Field<Boolean> field16() {
        return UserSettings.USER_SETTİNGS.İS_VİSİBLE_LAST_SEEN;
    }

    @Override
    public Field<Boolean> field17() {
        return UserSettings.USER_SETTİNGS.İS_VİSİBLE_PROFİLE_PİCTURE;
    }

    @Override
    public Field<Boolean> field18() {
        return UserSettings.USER_SETTİNGS.İS_VİSİBLE_EMAİL;
    }

    @Override
    public Field<Boolean> field19() {
        return UserSettings.USER_SETTİNGS.İS_VİSİBLE_RESUME;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public Long component2() {
        return getVersion();
    }

    @Override
    public String component3() {
        return getProcessStatus();
    }

    @Override
    public String component4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component6() {
        return getModificationDate();
    }

    @Override
    public UUID component7() {
        return getUserUuid();
    }

    @Override
    public String component8() {
        return getLanguage();
    }

    @Override
    public Boolean component9() {
        return getİsActiveDarkMode();
    }

    @Override
    public Boolean component10() {
        return getİsActiveEmailNotification();
    }

    @Override
    public Boolean component11() {
        return getİsActiveSmsNotification();
    }

    @Override
    public Boolean component12() {
        return getİsActivePushNotification();
    }

    @Override
    public Boolean component13() {
        return getİsActiveTwoFactorAuthentication();
    }

    @Override
    public Boolean component14() {
        return getİsVisibleLocation();
    }

    @Override
    public Boolean component15() {
        return getİsVisibleOnlineStatus();
    }

    @Override
    public Boolean component16() {
        return getİsVisibleLastSeen();
    }

    @Override
    public Boolean component17() {
        return getİsVisibleProfilePicture();
    }

    @Override
    public Boolean component18() {
        return getİsVisibleEmail();
    }

    @Override
    public Boolean component19() {
        return getİsVisibleResume();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public Long value2() {
        return getVersion();
    }

    @Override
    public String value3() {
        return getProcessStatus();
    }

    @Override
    public String value4() {
        return getRowStatus();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value6() {
        return getModificationDate();
    }

    @Override
    public UUID value7() {
        return getUserUuid();
    }

    @Override
    public String value8() {
        return getLanguage();
    }

    @Override
    public Boolean value9() {
        return getİsActiveDarkMode();
    }

    @Override
    public Boolean value10() {
        return getİsActiveEmailNotification();
    }

    @Override
    public Boolean value11() {
        return getİsActiveSmsNotification();
    }

    @Override
    public Boolean value12() {
        return getİsActivePushNotification();
    }

    @Override
    public Boolean value13() {
        return getİsActiveTwoFactorAuthentication();
    }

    @Override
    public Boolean value14() {
        return getİsVisibleLocation();
    }

    @Override
    public Boolean value15() {
        return getİsVisibleOnlineStatus();
    }

    @Override
    public Boolean value16() {
        return getİsVisibleLastSeen();
    }

    @Override
    public Boolean value17() {
        return getİsVisibleProfilePicture();
    }

    @Override
    public Boolean value18() {
        return getİsVisibleEmail();
    }

    @Override
    public Boolean value19() {
        return getİsVisibleResume();
    }

    @Override
    public UserSettingsRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public UserSettingsRecord value2(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public UserSettingsRecord value3(String value) {
        setProcessStatus(value);
        return this;
    }

    @Override
    public UserSettingsRecord value4(String value) {
        setRowStatus(value);
        return this;
    }

    @Override
    public UserSettingsRecord value5(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public UserSettingsRecord value6(LocalDateTime value) {
        setModificationDate(value);
        return this;
    }

    @Override
    public UserSettingsRecord value7(UUID value) {
        setUserUuid(value);
        return this;
    }

    @Override
    public UserSettingsRecord value8(String value) {
        setLanguage(value);
        return this;
    }

    @Override
    public UserSettingsRecord value9(Boolean value) {
        setİsActiveDarkMode(value);
        return this;
    }

    @Override
    public UserSettingsRecord value10(Boolean value) {
        setİsActiveEmailNotification(value);
        return this;
    }

    @Override
    public UserSettingsRecord value11(Boolean value) {
        setİsActiveSmsNotification(value);
        return this;
    }

    @Override
    public UserSettingsRecord value12(Boolean value) {
        setİsActivePushNotification(value);
        return this;
    }

    @Override
    public UserSettingsRecord value13(Boolean value) {
        setİsActiveTwoFactorAuthentication(value);
        return this;
    }

    @Override
    public UserSettingsRecord value14(Boolean value) {
        setİsVisibleLocation(value);
        return this;
    }

    @Override
    public UserSettingsRecord value15(Boolean value) {
        setİsVisibleOnlineStatus(value);
        return this;
    }

    @Override
    public UserSettingsRecord value16(Boolean value) {
        setİsVisibleLastSeen(value);
        return this;
    }

    @Override
    public UserSettingsRecord value17(Boolean value) {
        setİsVisibleProfilePicture(value);
        return this;
    }

    @Override
    public UserSettingsRecord value18(Boolean value) {
        setİsVisibleEmail(value);
        return this;
    }

    @Override
    public UserSettingsRecord value19(Boolean value) {
        setİsVisibleResume(value);
        return this;
    }

    @Override
    public UserSettingsRecord values(UUID value1, Long value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, UUID value7, String value8, Boolean value9, Boolean value10, Boolean value11, Boolean value12, Boolean value13, Boolean value14, Boolean value15, Boolean value16, Boolean value17, Boolean value18, Boolean value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserSettingsRecord
     */
    public UserSettingsRecord() {
        super(UserSettings.USER_SETTİNGS);
    }

    /**
     * Create a detached, initialised UserSettingsRecord
     */
    public UserSettingsRecord(UUID uuid, Long version, String processStatus, String rowStatus, LocalDateTime createdDate, LocalDateTime modificationDate, UUID userUuid, String language, Boolean isActiveDarkMode, Boolean isActiveEmailNotification, Boolean isActiveSmsNotification, Boolean isActivePushNotification, Boolean isActiveTwoFactorAuthentication, Boolean isVisibleLocation, Boolean isVisibleOnlineStatus, Boolean isVisibleLastSeen, Boolean isVisibleProfilePicture, Boolean isVisibleEmail, Boolean isVisibleResume) {
        super(UserSettings.USER_SETTİNGS);

        set(0, uuid);
        set(1, version);
        set(2, processStatus);
        set(3, rowStatus);
        set(4, createdDate);
        set(5, modificationDate);
        set(6, userUuid);
        set(7, language);
        set(8, isActiveDarkMode);
        set(9, isActiveEmailNotification);
        set(10, isActiveSmsNotification);
        set(11, isActivePushNotification);
        set(12, isActiveTwoFactorAuthentication);
        set(13, isVisibleLocation);
        set(14, isVisibleOnlineStatus);
        set(15, isVisibleLastSeen);
        set(16, isVisibleProfilePicture);
        set(17, isVisibleEmail);
        set(18, isVisibleResume);
    }
}
